### PR TITLE
ElementDragHelper: Fix drag NaN

### LINKED ISSUE #4635: Scrollview content disappears, Content entity recieving localPosition of NaN
While the debug console is opened and the Device toggler is set to mobile the scrollView Content localPosition sets to NaN. Scrollable content disappears. We noticed that this issue is present almost only if the Debug console is on and mobile mode is toggled. 

https://user-images.githubusercontent.com/10512039/189824028-b10012e0-5145-4603-9d9f-bf4eb56e169c.mp4

### Steps to Reproduce

1. Open https://playcanv.as/b/E9AhLZ7J/ or Fork the project https://playcanvas.com/editor/scene/1319039 and hit Launch
2. Open Dev Console and toggle the mobile view (setting the resolution to 407px x 745px or smaller) 
3. Hit Inventory / Toggle button
4. Drag the contents of the inventory ScrollView, !!! drag fast and nervous =)  so the cursor get's out of the browser's window. 
5. Check out the inventory-ui.js (lines 19-29) script for the console.trace() hook

### PR DESCRIPTION
**Pull request by kungfooman**
Fixes #4635 and #3748

The deltas in `ElementDragHelper#_onMove` become larger every frame, because one is using global position and the other takes local position... that goes well for a few frames, but then explodes into either extremely near 0 or Infinity. And in the case of Infinity it perpetuates itself further into NaN.

I also did some refactoring, which reduces the amount of code while using less method calls and less property lookups, which also reduces the amount of code.

It was quite some work to actually find the bug Infinity/NaN bug, so I added JSDoc along the way...

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by yaustar** [comment]
Where's the actual fix as you made some code improvements along the way that makes it hard to see the actual fix 😅

File: src/framework/components/element/element-drag-helper.js [hunk 1]
```diff
@@ -140,16 +140,16 @@ class ElementDragHelper extends EventHandler {
         this._determineInputPosition(event);
         this._chooseRayOriginAndDirection();
 
-        _planeOrigin.copy(this._element.entity.getPosition());
-        _planeNormal.copy(this._element.entity.forward).mulScalar(-1);
+        _plane.point.copy(this._element.entity.getLocalPosition());
```
Comment (kungfooman) [inline src/framework/components/element/element-drag-helper.js:143]: @yaustar this is the actual fix 😅

Comment (yaustar) [reply src/framework/components/element/element-drag-helper.js:143]: Oooh, that's interesting!

**Comment by kungfooman** [comment]
@yaustar Yes, this PR also fixes your issue https://github.com/playcanvas/engine/issues/3748:

fixMovingDragNaN

File: src/framework/components/element/component.js [hunk 2]
```diff
@@ -1001,6 +1012,14 @@ class ElementComponent extends Component {
         this.entity.setLocalPosition = Entity.prototype.setLocalPosition;
     }
 
+    /**
+     * Patched method for setting the position.
+     *
+     * @param {number|Vec3} x - The x coordinate or Vec3
+     * @param {number} y - The y coordinate
+     * @param {number} z - The z coordinate
+     * @returns {void}
```
Comment (willeastcott) [inline src/framework/components/element/component.js:1021]: This line is redundant so best to remove it.

File: src/framework/components/element/component.js [hunk 3]
```diff
@@ -1001,6 +1012,14 @@ class ElementComponent extends Component {
...
+     */
```
Comment (willeastcott) [inline src/framework/components/element/component.js:1022]: This JSDoc block presumably needs a @private tag?

Comment (willeastcott) [reply src/framework/components/element/component.js:1022]: Same for JSDocs on other `_` functions in this PR.

File: src/framework/components/element/component.js [hunk 4]
```diff
@@ -1563,10 +1589,15 @@ class ElementComponent extends Component {
...
 
-    // recalculates
-    // localAnchor, width, height, (local position is updated if anchors are split)
-    // assumes these properties are up to date
-    // _margin
+    /**
+     * recalculates
+     * localAnchor, width, height, (local position is updated if anchors are split)
+     * assumes these properties are up to date
+     * _margin
```
Comment (willeastcott) [inline src/framework/components/element/component.js:1596]: Reformat assuming a max columns of 100.

File: src/framework/components/element/component.js (hunk 2 above)
Comment (kungfooman) [reply src/framework/components/element/component.js]: It triggered a linting error because of `return Entity.prototype.setPosition.call(this, x, y, z);`, so I just changed that now to make it clearer that there is really no return value.

File: src/framework/components/element/component.js [hunk 5]
```diff
@@ -674,27 +679,33 @@ class ElementComponent extends Component {
...
+     * pc.app.root.findByName("Inventory").element.pivot = [Math.random() * 0.1, Math.random() * 0.1];
+     * @example
+     * pc.app.root.findByName("Inventory").element.pivot = new pc.Vec2(Math.random() * 0.1, Math.random() * 0.1);
+     *
+     * @type {Vec2 | number[]}
      */
     set pivot(value) {
-        const prevX = this._pivot.x;
-        const prevY = this._pivot.y;
+        const { _pivot, _margin } = this;
```
Comment (mvaligursky) [inline src/framework/components/element/component.js:690]: why local variables with _ ? I'd remove it.

File: src/framework/components/element/component.js [hunk 6]
```diff
@@ -1563,10 +1592,18 @@ class ElementComponent extends Component {
         this.off();
     }
 
-    // recalculates
-    // localAnchor, width, height, (local position is updated if anchors are split)
-    // assumes these properties are up to date
-    // _margin
+    /**
+     * recalculates
```
Comment (mvaligursky) [inline src/framework/components/element/component.js:1596]: If we make this jsdocs, it'd be good to format it nicer as well (even when private)

File: src/framework/components/element/element-drag-helper.js [hunk 7]
```diff
@@ -210,21 +210,21 @@ class ElementDragHelper extends EventHandler {
     }
 
     _onMove(event) {
-        if (this._element && this._isDragging && this.enabled && this._element.enabled && this._element.entity.enabled) {
+        const { _element, _deltaMousePosition, _deltaHandlePosition, _axis } = this;
+        if (_element && this._isDragging && this.enabled && _element.enabled && _element.entity.enabled) {
             const currentMousePosition = this._screenToLocal(event);
+            if (currentMousePosition) {
```
[the remark this answers is not in the document]
Comment (kungfooman) [reply src/framework/components/element/element-drag-helper.js:216]: @jpauloruschel Yes, its assigned in the constructor and never deleted. Also other code depends on it being never deleted, like this (line 122): https://github.com/playcanvas/engine/blob/6c7d3dc2dae80364dfedebb2bd371a48aba976d2/src/framework/components/element/element-drag-helper.js#L112-L128

Therefore checking if a reference exists (which always exists), is a no-op.

File: src/framework/components/element/component.js (hunk 5 above)
Comment (kungfooman) [reply src/framework/components/element/component.js:690]: Do you mean like `const { _pivot: pivot, _margin: margin } = this;` instead?

Comment (mvaligursky) [reply src/framework/components/element/component.js:690]: yep, that would do.

File: src/framework/components/element/component.js (hunk 6 above)
Comment (kungfooman) [reply src/framework/components/element/component.js:1596]: Okay, I worked it out a little bit: 
image

I renamed `localAnchor` to `_localAnchor` aswell, becaues there is no getter for `localAnchor`.

File: src/framework/components/element/component.js (hunk 5 above)
Comment (kungfooman) [reply src/framework/components/element/component.js:690]: I just realized its also possible to just write `const { pivot, margin } = this;`, since `get pivot()` is just returning `_pivot` anyway, which would decrease the amount of code here. Is that okay with you?

Comment (mvaligursky) [reply src/framework/components/element/component.js:690]: totally

File: src/framework/components/element/component.js [hunk 8]
```diff
@@ -397,13 +397,18 @@ class ElementComponent extends Component {
...
+     *
+     * @type {Vec4 | number[]}
      */
     set anchor(value) {
         if (value instanceof Vec4) {
-            this._anchor.set(value.x, value.y, value.z, value.w);
+            this._anchor.copy(value);
         } else {
-            this._anchor.set(value[0], value[1], value[2], value[3]);
+            this._anchor.set(...value);
```
Comment (mvaligursky) [inline src/framework/components/element/component.js:411]: one more tiny request .. I'd prefer to previous version of this line, as the changed version allocates an array internally I believe, I'd prefer to avoid that.

File: src/framework/components/element/component.js [hunk 9]
```diff
@@ -674,27 +679,33 @@ class ElementComponent extends Component {
...
+        const { pivot, margin } = this;
+        const prevX = pivot.x;
+        const prevY = pivot.y;
 
         if (value instanceof Vec2) {
-            this._pivot.set(value.x, value.y);
+            pivot.copy(value);
         } else {
-            this._pivot.set(value[0], value[1]);
+            pivot.set(...value);
```
Comment (mvaligursky) [inline src/framework/components/element/component.js:697]: and the same here.

File: src/framework/components/element/component.js (hunk 8 above)
Comment (kungfooman) [reply src/framework/components/element/component.js:411]: It's just using `.apply`, passing through the array.

Comment (mvaligursky) [reply src/framework/components/element/component.js:411]: ah right, the value is already array, I missed that somehow.

**Review by mvaligursky — APPROVED** [review]
Looks great, thanks for the work!

File: src/framework/components/element/component.js (hunk 9 above)
Comment (kungfooman) [reply src/framework/components/element/component.js:697]: Same here, the ES5 version is just something like:
```js
value = [1, 2, 3];
console.log.apply(null, value);
```
Is it okay to keep? I would argue it reduces the amount of stack pollution / needless array unpacking

Comment (mvaligursky) [reply src/framework/components/element/component.js:697]: I still believe the original code would run faster, but this is not critical path so it's ok.

**Review by jpauloruschel — APPROVED** [review]
