### PR TITLE
Include urlBase when loading gltf external assets

### LINKED ISSUE #1936: Loading glTF with external assets
### Description
I am trying to use the glTF support added in 1.26.0 but run into problems when loading `.gltf` files with references to external assets such as bins and images. The assets are referenced via URI and placed "side-by-side" the `.gltf` as such:

image

When i run `app.assets.loadFromUrl("path/to/model.gltf", "container", function (err, asset) {})` the callback is never fired and I get a bunch of 404 results in the network log. I see two issues here:

1. Instead of fetching external assets using the same base path as the loaded `.gltf` file, the engine tries to load the assets from the site root. This is the result in the network log:
image
I suggest a base path based on the `.gltf` path is automatically prepended to all external asset requests since the [glTF 2.0 spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#gltf-basics) says external files should be stored side-by-side the `.gltf`.

2. The callback of `app.assets.loadFromUrl(...)` is never fired when the external asset requests fail. I would assume the callback should be fired with an `err` argument in this case.

### Steps to Reproduce
1. Play the project https://playcanvas.com/project/673806/overview/gltfpathproblem
2. Note that the embedded `.gltf` loads correctly
3. Open network log and check how requests for external assets have failed

### PR DESCRIPTION
**Pull request by slimbuck**
Fixes #1936

This PR makes the following changes:
- use gltf urlBase when loading gltf external references
- make use of pc.http instead of XMLHttpRequest
- propagate download failures correctly to caller
- revert previous change to loadFromURL and introduce new function loadFromUrlAndFilename instead
- update example viewer to render on demand

API changes are as follows:
```javascript
loadFromUrl: function (url, type, callback);   // reverted previous change where filename was specified after callback
loadFromUrlAndFilename: function (url, filename, type, callback);  // new function which takes filename
```

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

File: src/asset/asset-registry.js [hunk 1]
```diff
@@ -447,13 +447,31 @@ Object.assign(pc, function () {
...
+         * @function
+         * @name pc.AssetRegistry#loadFromUrlAndFilename
+         * @description Use this to load and create an asset when both the URL and filename are required. For example, use this function when loading
+         * BLOB assets, where the URL does not adequately identify the file.
+         * @param {string} url - The url to load.
+         * @param {string} filename - The filename of the asset to load.
+         * @param {string} type - The type of asset to load.
+         * @param {pc.callbacks.LoadAsset} callback - Function called when asset is loaded, passed (err, asset), where err is null if no errors were encountered.
+         * @example
+         * var file = magiallyAttainAFile();
```
Comment (willeastcott) [inline src/asset/asset-registry.js]: magially? 😄

Comment (slimbuck) [reply src/asset/asset-registry.js]: lol - already fixed!
