### PR TITLE
Fixed examples device type logging

### LINKED ISSUE #7019: Tiny examples warning that should not be displayed
Repro steps:

- run any example, for example HelloWorld, in WebGPU mode
- switch to Compute -> Histogram example (which is only supported in WebGPU mode)
- it console log has warning:  `WebGL is disabled. Using WebGPU instead.`
- Ideally this should not be logged, as WebGL is not even considered as we're in persistent WebGPU mode from the previous example.

Tiny issue, but logging anyways.

### PR DESCRIPTION
**Pull request by kpal81xd**
Fixes #7019

### CODE REVIEW

File: examples/iframe/utils.mjs [hunk 1]
```diff
@@ -109,30 +109,29 @@ export let deviceType = 'webgl2';
  * @param {{ WEBGPU_DISABLED: boolean; WEBGL_DISABLED: boolean; }} config - The configuration object.
  */
 export function updateDeviceType(config) {
+    const savedDevice = localStorage.getItem('preferredGraphicsDevice') ?? 'webgl2';
+    deviceType = DEVICE_TYPES.includes(savedDevice) ? savedDevice : 'webgl2';
+
     if (params.deviceType && DEVICE_TYPES.includes(params.deviceType)) {
-        console.warn("Overwriting default deviceType from URL: ", params.deviceType);
+        console.warn("Overwriting default device: ", params.deviceType);
```
Comment (willeastcott) [inline examples/iframe/utils.mjs:116]: Should this say 'overriding'?

**Review by willeastcott — APPROVED** [review]
