### PR TITLE
[Anim Component] Fix exit time conditions for non looping animations

### LINKED ISSUE #4427: Anim transition with exit time of 1 is not triggered when conditions match after non looping state has finished
Thread: https://forum.playcanvas.com/t/anim-system-issues/26559

Project https://playcanvas.com/project/956796/overview/cant-exit-non-looping-state

Repro steps: 

Hold P to transition to the punch animation
Wait for the punch animation to finish
Release P

Expected result is that the graph should transition to the Idle state as the punch state has reached the end of the animation and is at exit time 1

Related to #4426 ?

### PR DESCRIPTION
**Pull request by ellthompson**
The anim controller shouldn't update the state time when a non looping animation has completed its playback. Additionally  states that have finished their playback should have their exit time conditions checked as if they were playing.

Fixes #4427

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

File: src/framework/anim/controller/anim-controller.js [hunk 1]
```diff
@@ -516,8 +521,17 @@ class AnimController {
         let state;
         let animation;
         let clip;
-        this._timeInStateBefore = this._timeInState;
-        this._timeInState += dt * this.activeState.speed;
+        // update time when looping or when the active state is not at the end of its duration
+        if (this.activeState.loop || this._timeInState < this.activeStateDuration) {
```
Comment (mvaligursky) [inline src/framework/anim/controller/anim-controller.js:525]: `this.activeStateDuration` is really expensive - it searches for animations by name, and it gets called here 4x ?

Comment (ellthompson) [reply src/framework/anim/controller/anim-controller.js:536]: I've added a flag to the calculation of the current states duration. It'll now be calculated at most once per state transition or assignment of a new animation file.

**Review by mvaligursky — APPROVED** [review]
