### PR TITLE
Fixed errors in TypeScript Declarations

### LINKED ISSUE #1656: Errors in TypeScript Declarations
### Description

We encounter the following errors when trying to use the auto-generated `playcanvas.d.ts` in TypeScript:

```
playcanvas.d.ts(12881,24): error TS1110: Type expected.
```

And if manually fixed by changing line 12881 from  `default?: ?;` to `default?: any;` (in `playcanvas.d.ts`), then the remaining errors will be shown.

```
playcanvas.d.ts(623,39): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
playcanvas.d.ts(1550,41): error TS1016: A required parameter cannot follow an optional parameter.
playcanvas.d.ts(1861,32): error TS2694: Namespace 'pc' has no exported member 'LayoutChildComponentSystem'.
playcanvas.d.ts(1904,32): error TS2694: Namespace 'pc' has no exported member 'LayoutGroupComponentSystem'.
playcanvas.d.ts(3120,32): error TS2694: Namespace 'pc' has no exported member 'SpriteComponentSystem'.
playcanvas.d.ts(5992,85): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
playcanvas.d.ts(7724,33): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
playcanvas.d.ts(7744,38): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
playcanvas.d.ts(7744,46): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
playcanvas.d.ts(7908,18): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
playcanvas.d.ts(10113,12): error TS1016: A required parameter cannot follow an optional parameter.
playcanvas.d.ts(10146,12): error TS1016: A required parameter cannot follow an optional parameter.
playcanvas.d.ts(10179,12): error TS1016: A required parameter cannot follow an optional parameter.
playcanvas.d.ts(10213,12): error TS1016: A required parameter cannot follow an optional parameter.
playcanvas.d.ts(10248,12): error TS1016: A required parameter cannot follow an optional parameter.
playcanvas.d.ts(10282,46): error TS2694: Namespace 'pc' has no exported member 'ResourceHandler'.
playcanvas.d.ts(10401,36): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
playcanvas.d.ts(10471,29): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
playcanvas.d.ts(10492,32): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
playcanvas.d.ts(10492,101): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
playcanvas.d.ts(10502,31): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
playcanvas.d.ts(10511,53): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
playcanvas.d.ts(11341,41): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
playcanvas.d.ts(11349,44): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
playcanvas.d.ts(11383,41): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
playcanvas.d.ts(11390,44): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
playcanvas.d.ts(11423,95): error TS2694: Namespace 'pc' has no exported member 'ForwardRenderer'.
playcanvas.d.ts(11423,120): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
playcanvas.d.ts(11490,51): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
playcanvas.d.ts(11588,51): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
playcanvas.d.ts(11882,51): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
playcanvas.d.ts(12664,29): error TS2694: Namespace 'pc' has no exported member 'SPRITE_RENDERMODE'.
playcanvas.d.ts(13401,31): error TS2749: 'Audio' refers to a value, but is being used as a type here.
```

### Steps to Reproduce

0. Clone the repo and checkout `master` and run `npm install` (if you haven't already)
1. Run `npm run tsd`, to generate `build/output/playcanvas.d.ts`
2. Run `npm install --only=dev typescript`, to temporarily add the TypeScript compiler locally
3. Run `npx tsc ./build/output/playcanvas.d.ts --pretty false`, to check declarations for errors

### PR DESCRIPTION
**Pull request by aidinabedi**
Fixes #1656

PR includes:
- Fixed ambiguous arrays by using type-specific arrays in jsdoc comments.
- Fixed unrecognized types (`?` and `Audio`) in jsdoc comments.
- Fixed issue `required parameter following optional parameter` by adding jsdoc function varations.
- Fixed missing types referenced in public documentation by removing some `@private` tags.
- Fixed unresolved types by adding missing `@constructor` tags.
- Fixed missing reference to `pc.ResourceHandler` by adding simple interface declaration.
- Fixed issue with using type `pc.SPRITE_RENDERMODE` in jsdoc, since it is not a strict jsdoc enum type.
- Added missing jsdoc comments for default instance `pc.http`. 

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

File: src/resources/handler.js [hunk 1]
```diff
@@ -0,0 +1,37 @@
+Object.assign(pc, function () {
+    'use strict';
+
+    /**
+     * @interface pc.ResourceHandler
```
Comment (willeastcott) [inline src/resources/handler.js]: What's this file for? It's not actually used by the sourcebase in this PR.

File: src/net/http.js [hunk 2]
```diff
@@ -56,9 +56,24 @@ Object.assign(pc, function () {
         /**
          * @function
          * @name pc.Http#get
+         * @variation 1
```
Comment (willeastcott) [inline src/net/http.js]: Have you checked the JSdoc output to see what output from the variation tag looks like? I've never used it before...

File: src/math/mat3.js [hunk 3]
```diff
@@ -1,243 +1,243 @@
-Object.assign(pc, (function () {
```
Comment (willeastcott) [inline src/math/mat3.js]: Why has every line in this JS file been marked as changed? I'm a bit worried about merging if we make diffing harder.

Comment (aidinabedi) [reply src/math/mat3.js]: Because of line-endings. I've tried multiple times to commit only the few changed lines but for some reason the EOL is constantly being corrected. Is there something wrong with the EOLs in the original file?

File: src/resources/handler.js (hunk 1 above)
Comment (aidinabedi) [reply src/resources/handler.js]: The original jsdoc comments references pc.ResourceHandler as a type (in `resources/loader.js` and `resources/model.js`). But since there is no interface declaration for pc.ResourceHandler, the TypeScript declarations break.

I just now also added it to `dependencies.txt` so that it is included. This way devs can use it as a documented base class for their custom handlers (which we need).

File: src/net/http.js (hunk 2 above)
Comment (aidinabedi) [reply src/net/http.js]: Of course. Both `d.ts` and `html` output is two separate functions, with and without param `options`.

File: src/resources/handler.js (hunk 1 above)
Comment (willeastcott) [reply src/resources/handler.js]: @daredevildave You wrote this code - what would you like to happen here?

File: src/net/http.js (hunk 2 above)
Comment (willeastcott) [reply src/net/http.js]: @daredevildave Are any of the variations of the signatures of pc.http functions deprecated/private? This will expose them as public API.

Comment (daredevildave) [reply src/net/http.js]: seems fine

File: src/resources/handler.js (hunk 1 above)
Comment (daredevildave) [reply src/resources/handler.js]: I think it needs a patch function too? But otherwise it seems fine.

Comment (aidinabedi) [reply src/resources/handler.js]: @daredevildave Good point. Patch function added.

**Comment by willeastcott** [comment]
This PR actually causes linting to fail now. pc.ResourceHandler#open has a returns JSdoc tag but not return in the code.

**Comment by aidinabedi** [comment]
@willeastcott Tweaked PR (#1659) which fixes the lint issue.
