### PR TITLE
Assets fix

### LINKED ISSUE #2892: asset.getFileUrl() throws TypeError
Texture type (more complicated because of variants):

```js
asset = new pc.Asset("Test", "texture", {
        url: "test.jpg"
    });
asset.getFileUrl()
```

HTML:

```js
asset = new pc.Asset("Test", "html", {
        url: "test.html"
    });
asset.getFileUrl()
```

Result for both:

image

It starts to work as soon the asset is added to registry:

```js
asset = new pc.Asset("Test", "texture", {
        url: "test.jpg"
    });
app.assets.add(asset)
asset.getFileUrl()
```

image

So this is not a big deal, yet maybe it would be good to not throw errors by accessing undefined variables? Some people will run into this and wonder what goes on (at least I did 😅).

### PR DESCRIPTION
**Pull request by slimbuck**
Fixes #2892

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

File: src/asset/asset.js [hunk 1]
```diff
@@ -192,29 +193,30 @@ class Asset extends EventHandler {
...
-
-                // if the variant does not exist but the asset is in a bundle
-                // and the bundle contain assets with this variant then return the default
-                // file for the asset
-                if (app.enableBundles) {
-                    var bundles = app.bundles.listBundlesForAsset(this);
-                    if (! bundles) continue;
+            var app = this.registry?._loader?._app || getApplication();
+            var device = app?.graphicsDevice;
+            if (device) {
```
Comment (yaustar) [inline src/asset/asset.js:198]: We should return null or the original URL if no device is found?

Comment (yaustar) [reply src/asset/asset.js:198]: Oh wait, it does. Couldn't see it in the diff 😅

**Review by yaustar — APPROVED** [review]
Looks fine. This pattern is done elsewhere so it's inline with the rest of the engine

**Review by mvaligursky — APPROVED** [review]
