### PR TITLE
Clear mask stencil, add Screen priority

### LINKED ISSUE #1174: Multiple nested masks can interfere
If you place two mask image elements under a parent mask, their masks are combined into a single mask, instead of two separately masked areas.

### Steps to Reproduce

1. Create 2D screen with a single Image element child, enable masking on that child 
2. Create two child image elements for the mask element, place them side by side and enable masking
3. Create an new child under one of the children masks, make it wide enough to appear in both child masks

Note that the child is rendered under both masks. It should only appear in the mask that is it's parent.

### PR DESCRIPTION
**Pull request by daredevildave**
* Clear mask stencil after all mask children are rendered by re-rendering with new stencil params
* Add ScreenComponent.priority property to set order of screen rendering

Fixes #1174

### CODE REVIEW

File: src/framework/components/element/component.js [hunk 1]
```diff
@@ -444,99 +456,98 @@ Object.assign(pc, function () {
...
+                    this._image._maskRef = depth;
+
+                    // increment counter to count mask depth
+                    depth++;
 
-                    mask = this.entity;
+                    if (_debugLogging) {
+                        console.log("masking from: " + this.entity.name + " with " + (sp.ref+1));
+                        console.log("depth++ to: ", depth);
+                    }
```
Comment (willeastcott) [inline src/framework/components/element/component.js]: Should all this debugging stuff be deleted now?

File: src/framework/components/element/component.js [hunk 2]
```diff
@@ -444,99 +456,98 @@ Object.assign(pc, function () {
...
+                    this._image._setStencil(sp);
+                    this._image._maskRef = depth;
+
+                    // increment mask counter to count depth of masks
+                    depth++;
+
+                    if (_debugLogging) {
+                        console.log("masking from: " + this.entity.name + " with " + sp.ref);
+                        console.log("depth++ to: ", depth);
+                    }
```
Comment (willeastcott) [inline src/framework/components/element/component.js]: Remove?

File: src/framework/components/element/component.js [hunk 3]
```diff
@@ -905,7 +921,18 @@ Object.assign(pc, function () {
...
-            this._drawOrder = value;
+            var priority = 0;
+            if (this.screen) {
+                priority = this.screen.screen.priority;
+            }
+
+            if (value > 0xFFFFFF) {
+                console.error("Element.drawOrder larger than max size of: " + 0xFFFFFF);
+                value = 0xFFFFFF;
+            }
```
Comment (willeastcott) [inline src/framework/components/element/component.js]: Wrap in the DEBUG preprocessor?

File: src/framework/components/element/image-element.js [hunk 4]
```diff
@@ -1,4 +1,203 @@
...
+            } else {
+                this.unmaskMeshInstance.drawOrder = this.meshInstance.drawOrder + this._element.getMaskOffset();
+            }
+
+            // maskOffset -= maskOffsetIncrement;
+            // if (maskOffset < 0) {
+            //     maskOffset = maskOffsetIncrement;
+            //     console.warn('Unmasking offset reached 0. Defaulting to ' + maskOffsetIncrement);
+            // }
+            if (_debugLogging) console.log('setDrawOrder: ', this.unmaskMeshInstance.name, this.unmaskMeshInstance.drawOrder);
```
Comment (willeastcott) [inline src/framework/components/element/image-element.js]: Remove?

File: src/framework/components/element/image-element.js [hunk 5]
```diff
@@ -1,4 +1,203 @@
...
+        }
+    };
+
+    ImageRenderable.prototype.setDrawOrder = function (drawOrder) {
+        if (_debugLogging) console.log('setDrawOrder: ', this.meshInstance.name, drawOrder);
```
Comment (willeastcott) [inline src/framework/components/element/image-element.js]: Remove?

File: src/framework/components/element/image-element.js [hunk 6]
```diff
@@ -63,15 +253,17 @@ Object.assign(pc, function () {
...
+            this._renderable.destroy();
+            // if (this._model) {
+            //     this._element.removeModelFromLayers(this._model);
+            //     // reset mesh to the default because that's the mesh we want destroyed
+            //     // and not possible a mesh from the sprite asset that might be
+            //     // used elsewhere
+            //     this._meshInstance.mesh = this._defaultMesh;
+            //     this._model.destroy();
+            //     this._model = null;
+            // }
```
Comment (willeastcott) [inline src/framework/components/element/image-element.js]: Remove?
