### PR TITLE
[AnimComponent] First frame bug fix

### LINKED ISSUE #3533: Problem when speed of anim component is 0 at start
### Description
In my own project my character is not visible (probably out of camera view) when the speed of the anim component is set to 0. In the third person tutorial the character is visible but on a different position and in T-pose. I use this project to show the problem, after a second I set the speed back to 1 by script. 

Probably these results are to be expected because a speed of 0 doesn't start the animation at all, but personally I would see the animation start first and then use the speed of 0.

https://launch.playcanvas.com/1242536?debug=true

### Anim speed of 0:
image
image

### Anim speed of 1:
image
image

### PR DESCRIPTION
**Pull request by ellthompson**
The first update of the anim component created a divide by 0 error, which caused the output values of all animations during the initial frame to contain incorrect values.

Fixes #3533 

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Review by mvaligursky — APPROVED** [review]

File: src/anim/controller/anim-controller.js [hunk 1]
```diff
@@ -521,7 +522,7 @@ class AnimController {
         if (this._isTransitioning) {
             this._currTransitionTime += dt;
             if (this._currTransitionTime <= this._totalTransitionTime) {
-                const interpolatedTime = this._currTransitionTime / this._totalTransitionTime;
+                const interpolatedTime = this._totalTransitionTime ? this._currTransitionTime / this._totalTransitionTime : 1;
```
Comment (yaustar) [inline src/anim/controller/anim-controller.js:524]: Should we explicitly check against 0 here?

File: src/framework/components/anim/component.js [hunk 2]
```diff
@@ -344,6 +344,7 @@ class AnimComponent extends Component {
             this._addLayer.bind(this)({ ...layer });
         }
         this.setupAnimationAssets();
+        console.log('here');
```
Comment (yaustar) [inline src/framework/components/anim/component.js]: Remove debugging code :)

**Review by yaustar — APPROVED** [review]
Approved with comments

**Comment by yaustar** [comment]
Cool, I will need to update this tutorial! https://developer.playcanvas.com/en/tutorials/world-to-ui-screen-space/
