### PR TITLE
improve GrabPass and fix rendertarget issue

### LINKED ISSUE #1640: Grab-Pass not working when using rendertarget
### Description
A custom shader (that uses the existing global `texture_grabPass` uniform) will not work if the camera has a post-effect instead of rendering directly to the canvas. This is because the `grabPass` texture has the canvas as the only source.

### Steps to Reproduce
1. Run public project: https://playcanvas.com/project/630510/overview/grabpass-rendertarget-test
2. Observe black issue with `Box` models that use custom shader with `texture_grabPass`.
3. Disable post-effect script `Sepia` on `Camera`, and note that it starts working.

### What I expect to see
image

### What I see instead
image

### What I see without a rendertarget
image

### PR DESCRIPTION
**Pull request by aidinabedi**
Fixes #1640

The PR includes the following:
- Improve code path readability for grabpass by keeping it simple and separate (use `device.updateGrabPass` instead of `device.uploadTexture`).
- Use `gl.copyTexImage2D` (which is source-type-independent) instead of `gl.texImage2D` (which doesn't support a rendertarget as source).
- Optimize grabpass by ignoring the alpha channel if the canvas doesn't have transparency.

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

File: src/graphics/device.js [hunk 1]
```diff
@@ -879,21 +879,22 @@ Object.assign(pc, function () {
...
+                addressV: pc.ADDRESS_CLAMP_TO_EDGE,
+                mipmaps: false
             });
 
-            grabPassTexture.minFilter = pc.FILTER_LINEAR;
-            grabPassTexture.magFilter = pc.FILTER_LINEAR;
-            grabPassTexture.addressU = pc.ADDRESS_CLAMP_TO_EDGE;
-            grabPassTexture.addressV = pc.ADDRESS_CLAMP_TO_EDGE;
-
+            grabPassTexture._pot = false; // never treat texture as "power of 2", framebuffer size is arbitrary.
```
Comment (willeastcott) [inline src/graphics/device.js]: I'm not super-keen on _pot being accessed here, TBH. Looking at pc.Texture, we could probably lose this property and just calculate on demand since it's not really performance critical. But let's leave that for another PR.

File: src/graphics/device.js [hunk 2]
```diff
@@ -879,21 +879,22 @@ Object.assign(pc, function () {
...
+
             var grabPassTexture = new pc.Texture(this, {
-                format: pc.PIXELFORMAT_R8_G8_B8_A8,
-                autoMipmap: false
+                format: format,
+                minFilter: pc.FILTER_LINEAR,
+                magFilter: pc.FILTER_LINEAR,
+                addressU: pc.ADDRESS_CLAMP_TO_EDGE,
+                addressV: pc.ADDRESS_CLAMP_TO_EDGE,
+                mipmaps: false
```
Comment (willeastcott) [inline src/graphics/device.js]: So does the grab pass texture now never have correct ```width``` and ```height``` set?

File: src/graphics/device.js [hunk 3]
```diff
@@ -902,6 +903,20 @@ Object.assign(pc, function () {
...
 
+        updateGrabPass: function () {
+            var gl = this.gl;
+
+            var format = this.grabPassTexture._glFormat;
+            var source = (this.renderTarget && this.renderTarget.colorBuffer) || this.canvas;
+            gl.copyTexImage2D(gl.TEXTURE_2D, 0, format, 0, 0, source.width, source.height, 0);
+        },
+
+        unnitializeGrabPass: function () {
```
Comment (willeastcott) [inline src/graphics/device.js]: Uninitialize doesn't have two 'n's, as far as I'm aware. However, shouldn't this instead be called destroyGrabPass to be more in line with other API naming conventions?

File: src/graphics/device.js (hunk 2 above)
Comment (aidinabedi) [reply src/graphics/device.js]: Nop, and we don't actually need to since the texture is not meant to be used by js.

File: src/graphics/device.js (hunk 3 above)
Comment (aidinabedi) [reply src/graphics/device.js]: I thought about naming it `destroyGrabPass` but then `initializeGrabPass` should probably also be renamed `createGrabPass` for symmetry. The only problem I see with that is it may give the impression to the reader that `createGrabPass` will return an object and `destroyGrabPass` takes a value and both are "pure" functions without side-effects.

File: src/graphics/device.js (hunk 1 above)
Comment (aidinabedi) [reply src/graphics/device.js]: I can just set `width` and `height` to zero.

File: src/graphics/device.js [hunk 4]
```diff
@@ -879,21 +879,22 @@ Object.assign(pc, function () {
             this.transformFeedbackBuffer = null;
         },
 
-        initializeGrabPassTexture: function () {
+        initializeGrabPass: function (options) {
```
[the remark this answers is not in the document]
Comment (aidinabedi) [reply src/graphics/device.js]: Fair enough.

**Comment by aidinabedi** [comment]
PR is updated per feedback.

**Comment by willeastcott** [comment]
OK, this is awesome - I think we're good to merge. 🎉
