### PR TITLE
Fix/local-axis-gizmo-error

### LINKED ISSUE #7012: Gizmo jumps to its parent when being transformed with local space
### Description

Gizmo jumps to its parent when being transformed with local space

https://github.com/user-attachments/assets/136e32b1-9a02-4c02-bcb1-d105fed620b3

### Steps to Reproduce

1. go to the gizmo example https://playcanvas.vercel.app/#/gizmos/transform-translate
2. Add the box to a parent entity and transform that entity a small amount
3. reload, switch to local transform and attempt to move the box, see it jumps position

### PR DESCRIPTION
**Pull request by MAG-ME**
Fixes #7012

Use the correct original values when updating transforms in local space transforms.

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

File: src/extras/gizmo/rotate-gizmo.js [hunk 1]
```diff
@@ -436,9 +431,19 @@ class RotateGizmo extends TransformGizmo {
             tmpQ1.setFromAxisAngle(tmpV1, angleDelta);
 
             if (!isFacing && this._coordSpace === GIZMOSPACE_LOCAL) {
+                const rot = this._nodeLocalRotations.get(node);
+                if (!rot) {
+                    continue;
+                }
+
```
Comment (kpal81xd) [inline src/extras/gizmo/rotate-gizmo.js:438]: Please remove extra lines to pass linting

**Review by kpal81xd — CHANGES_REQUESTED** [review]

File: src/extras/gizmo/rotate-gizmo.js (hunk 1 above)
Comment (MAG-ME) [reply src/extras/gizmo/rotate-gizmo.js]: Removed

**Review by kpal81xd — APPROVED** [review]
