### PR TITLE
LayerComposition dirtyBlend update fix

### LINKED ISSUE #2544: bug in function LayerComposition.prototype._update
1.sory for my poor english 
2.in following block 
"this._dirtyBlend = dirtyBlend1 || dirtyBlend2" seems should be:
"this._dirtyBlend = this._dirtyBlend || dirtyBlend1 || dirtyBlend2" or
"if(dirtyBlend1 || dirtyBlend2) this._dirtyBlend = true"

// rebuild this._meshInstances array - add all unique meshInstances from all layers to it
    // also set this._dirtyBlend to true if material of any meshInstance has _dirtyBlend set, and clear those flags on materials
    if (this._dirty) {
        result |= COMPUPDATED_INSTANCES;
        this._meshInstances.length = 0;
        this._meshInstancesSet.clear();
        var dirtyBlend1, dirtyBlend2;

        for (i = 0; i < len; i++) {
            layer = this.layerList[i];
            if (!layer.passThrough) {

                // add meshInstances from both opaque and transparent lists
                dirtyBlend1 = addUniqueMeshInstance(this._meshInstances, this._meshInstancesSet, layer.opaqueMeshInstances);
                dirtyBlend2 = addUniqueMeshInstance(this._meshInstances, this._meshInstancesSet, layer.transparentMeshInstances);
                this._dirtyBlend = dirtyBlend1 || dirtyBlend2; //*** here 
            }

            layer._dirty = false;
            layer._version++;
        }

        this._dirty = false;
    }

### PR DESCRIPTION
**Pull request by mvaligursky**
Fixes #2544

### CODE REVIEW

**Review by slimbuck — APPROVED** [review]

File: src/scene/layer-composition.js [hunk 1]
```diff
@@ -140,16 +140,14 @@ LayerComposition.prototype._update = function () {
...
 
         for (i = 0; i < len; i++) {
             layer = this.layerList[i];
             if (!layer.passThrough) {
 
                 // add meshInstances from both opaque and transparent lists
-                dirtyBlend1 = addUniqueMeshInstance(this._meshInstances, this._meshInstancesSet, layer.opaqueMeshInstances);
-                dirtyBlend2 = addUniqueMeshInstance(this._meshInstances, this._meshInstancesSet, layer.transparentMeshInstances);
-                this._dirtyBlend = dirtyBlend1 || dirtyBlend2;
+                this._dirtyBlend = addUniqueMeshInstance(this._meshInstances, this._meshInstancesSet, layer.opaqueMeshInstances) || this._dirtyBlend;
```
Comment (willeastcott) [inline src/scene/layer-composition.js:149]: Uhm. Shouldn't this be:
```
this._dirtyBlend = addUniqueMeshInstance(this._meshInstances, this._meshInstancesSet, layer.opaqueMeshInstances);
```

Comment (slimbuck) [reply src/scene/layer-composition.js:149]: No it can't. `addUniqueMeshInstance()` must be executed but `||=` operator short circuits.

Comment (willeastcott) [reply src/scene/layer-composition.js:149]: Ah ok
