### PR TITLE
Keyboard - remove presses when window is blurred or becomes hidden

### LINKED ISSUE #2855: app.keyboard.isPressed() remains true after switching Tab and coming back to same tab
if any key is pressed and the tab is switched, Then the key remains pressed after coming back to the same tab if it's pressed up before coming to this tab.

The first person movement project has this same issue. Here is a link to the project :
https://playcanvas.com/editor/scene/440123

Steps to reproduce:
1- Press any control Key e.g W/UP
2- Change Tab while keeping that key pressed.
3- After changing tab, press up that key and come back to the build (fps) tab.

### PR DESCRIPTION
**Pull request by Maksims**
Fixes #2855

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

File: src/input/keyboard.js [hunk 1]
```diff
@@ -226,6 +232,17 @@ class Keyboard extends EventHandler {
...
+    _handleVisibilityChange() {
+        if (document.visibilityState === 'hidden') {
+            this._handleWindowBlur();
+        }
+    }
+
+    _handleWindowBlur() {
+        this._keymap = {};
+        this._lastmap = {};
+    }
```
Comment (yaustar) [inline src/input/keyboard.js:244]: Will we need to fire keyup events so that the application can handle keys being 'released' by window blur?

Comment (Maksims) [reply src/input/keyboard.js:244]: I thought about it. But we won't be able to do that without faking Event object.
In the web, keydown > keyup - is not a guaranteed flow, so we probably should not change or try to mitigate it, as there will be a lot of edge cases.

This PR only focuses on static access to key states, not events. That would need to be a separate PR.

Comment (yaustar) [reply src/input/keyboard.js:244]: Right, I see what you mean

**Review by yaustar — APPROVED** [review]
