### PR TITLE
[FIX] Free shadowmap VRAM on destroying lights

### LINKED ISSUE #1050: Removing lights that cast shadows don't decrease the allocated texture memory in the profiler
The VRAM allocated for shadowmaps is only increasing, even though you might be removing/destroying entities that reference light components that cast shadows.

Step to reproduce:

1. Create a blank project

2. Launch with the profiler enabled

3. Start creating and destroying light entities that cast shadows.

You will notice that shadowmaps VRAM only increase, never decreasing.

### LINKED ISSUE #1183: shawdowmaps bug?
Dear PlayCanvas,

I want to give a bug report.

Launch:  https://launch.playcanvas.com/475211?debug=true&profile=true
Project:  https://playcanvas.com/project/437633/overview/changing-scenes

Situation:
The size of shadowmaps increases with every scene change, leading to slow down on mobile devices after a few scene changes.
It seems like shawdowmaps is not properly flushed, is this a bug? 
If so, please fix as soon as possible.

thanks! 

shadowmap bug

### PR DESCRIPTION
**Pull request by willeastcott**
Correctly free up VRAM associated with lights that cast shadowmaps.

Fixes #1050. 
Fixes #1183.

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

File: src/framework/components/light/system.js [hunk 1]
```diff
@@ -67,6 +67,11 @@ pc.extend(pc, function () {
             LightComponentSystem._super.initializeComponentData.call(this, component, data, _props);
         },
 
+        removeComponent: function (entity) {
```
Comment (daredevildave) [inline src/framework/components/light/system.js]: Note: most newer components subscribe to 'beforeremove' or 'remove' events and handle this there. e.g. See ElementComponentSystem

If you want to override removeComponent, you need to make sure you call the parent class removeComponent method too. e.g. See ModelComponentSystem

Also note: LightComponentSystem is subscribing to 'remove' event already, but doesn't seem to have implemented the method.

Comment (willeastcott) [reply src/framework/components/light/system.js]: Fixed! 😀
