### PR TITLE
Respect assets.prefix with loadFromUrl

### LINKED ISSUE #1765: AssetRegistry.prefix is added multiple times to final url
### Description

AssetRegistry.prefix is added multiple times to final url during loading of model's files.
Files are:

assets/eyeball/Eyeball.json
assets/eyeball/Eyeball.mapping.json
assets/eyeball/25649360/Material.json
assets/eyeball/25649362/eye-texture.jpg

### Steps to Reproduce
```// Create array with assets to load
let assets: pc.Asset[] = [];

assets.push(new pc.Asset("modBall", pc.eAssetType.model, { url: "eyeball/Eyeball.json" }));
        
// Load assets
let loaded = 0;
let toLoad = 0;

this._app.assets.prefix = "assets/";

assets.forEach((asset: pc.Asset) => {
	this._app.assets.add(asset);
     	toLoad++;
});

assets.forEach((asset: pc.Asset) => {
	this._app.assets.loadFromUrl(asset.file.url as string, asset.type, () => {
        	if (++loaded == toLoad)
                	clb.call(this);
    	});
});
```
The output in debug console is: 

> Error loading material: assets/assets/eyeball/25649360/Material.json [404]

### PR DESCRIPTION
**Pull request by Maksims**
Fixes #1765

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

File: src/asset/asset-registry.js [hunk 1]
```diff
@@ -531,6 +531,13 @@ Object.assign(pc, function () {
 
         // private method used for engine-only loading of model data
         _loadMaterials: function (dir, mapping, callback) {
+            if (dir) {
+                dir += '/';
```
Comment (willeastcott) [inline src/asset/asset-registry.js]: Should you check that the dir doesn't already end in a forward slash? Two forward slashes together are treated like a jump back to root.

Comment (Maksims) [reply src/asset/asset-registry.js]: In this case, `_loadMaterials` is private and `dir` that is passed to it, is a result of `pc.path.getDirectory(url)` - which returns path without trailing slashes.

Comment (willeastcott) [reply src/asset/asset-registry.js]: OK, sounds good, although that's not obvious from the code so I've added some code comments to clarify. Merging now... 😄
