### PR TITLE
Instantiate GLB's with correct AppBase instance

### LINKED ISSUE #7471: Error when sharing Assets between Application instances
Consider a single page displaying a gallery models/assets. There are  multiple `AppBase` instances and a single set of `Assets` shared across multiple app instances. 

This [currently throws a rendering error](https://codesandbox.io/p/sandbox/7prvzh?file=%2Fsrc%2Fmain.js%3A10%2C1) presumable because resource cannot be shared. However, it's not clear for the user what is wrong, or how to fix it. If assets can't be shared we should provide better feedback and warnings

This is a real world user issue See https://github.com/playcanvas/react/issues/80

### PR DESCRIPTION
**Pull request by marklundin**
Ensures that the correct `AppBase` instance is used when creating GLB's via `instantiateRenderEntity()`.  This uses the `Asset` reference to the app rather than `getApplication()` which can be incorrect.

Includes a tests. Fixes #7471 

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

File: src/framework/parsers/glb-container-resource.js [hunk 1]
```diff
@@ -123,7 +123,7 @@ class GlbContainerResource {
         // helper function to recursively clone a hierarchy of GraphNodes to Entities
         const cloneHierarchy = (root, node, glb) => {
 
-            const entity = new Entity();
+            const entity = new Entity('Untitled', this._assets._loader._app);
```
Comment (mvaligursky) [inline src/framework/parsers/glb-container-resource.js:126]: just pass `undefined` instead of 'Untitled', let the underlaying code handle the default

Comment (mvaligursky) [reply src/framework/parsers/glb-container-resource.js:126]: also update instantiateModelEntity the same way pls

Comment (marklundin) [reply src/framework/parsers/glb-container-resource.js]: done

**Review by mvaligursky — APPROVED** [review]
Look good. It's only a partial fix, there are still many cases this can load, as there are many entities created by us or the clients without passing the app to the constructor, but I hit this specific case before as well, so good to have this fixed.
