### PR TITLE
Handle anim events during reverse playback

### LINKED ISSUE #3808: Make anim events fire for reversed anims.
### Description

Make anim events work when an animation is running in reverse due to using a negative speed setting.

### Steps to Reproduce

In the Animation Events example, if you swap the sign on the speed, the anim events don't fire:

`113: modelEntity.anim.assignAnimation("Walk", walkTrack, undefined, -0.62);`

### LINKED ISSUE #4426: Anim event set at time 0 is fired at the start and end of a non looping animation
Thread: https://forum.playcanvas.com/t/anim-system-issues/26559/

Project: https://playcanvas.com/project/956782

Anim Event is set on both non looping animations at time 0

The event is fired at the start of the animation and at the end

### PR DESCRIPTION
**Pull request by ellthompson**
Setting an anim component state's speed to anything below zero would stop anim events firing during playback. The `activeEventsForFrame` function has been made agnostic to the direction of playback.

Fixes #3808
Fixes #4426

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

File: src/framework/anim/evaluator/anim-clip.js [hunk 1]
```diff
@@ -104,35 +105,98 @@ class AnimClip {
...
+        return this.isReverse ? 0 : this._track.events.length - 1;
+    }
+
+    get nextEvent() {
+        return this._track.events[this._eventCursor];
+    }
+
+    get isReverse() {
+        return this._speed < 0;
+    }
```
Comment (yaustar) [inline src/framework/anim/evaluator/anim-clip.js:118]: What if speed was 0. Could that cause an issue with any logic?

Comment (ellthompson) [reply src/framework/anim/evaluator/anim-clip.js:118]: Clips won't update events when the speed is 0 so there's no change in behaviour here.

File: src/framework/anim/evaluator/anim-clip.js [hunk 2]
```diff
@@ -104,35 +105,101 @@ class AnimClip {
...
+        if (this._eventCursor >= this.track.events.length) {
+            this._eventCursor = 0;
+        } else if (this._eventCursor < 0) {
+            this._eventCursor = this.track.events.length - 1;
         }
-        let clippedFrameDuration;
+    }
+
+    clipFrameTime(frameEndTime) {
+        const result = {
```
Comment (mvaligursky) [inline src/framework/anim/evaluator/anim-clip.js:147]: can we find a solution that does not allocate the object here?

File: src/framework/anim/evaluator/anim-clip.js [hunk 3]
```diff
@@ -66,6 +66,7 @@ class AnimClip {
 
     set speed(speed) {
         this._speed = speed;
+        this.alignCursorToCurrentTime();
```
Comment (mvaligursky) [inline src/framework/anim/evaluator/anim-clip.js:69]: should this be called only when the sign changes?

Comment (mvaligursky) [reply src/framework/anim/evaluator/anim-clip.js:69]: but even then, it seems strange to change the start index for events when the speed changes, as at this point the time has not changed?

File: src/framework/anim/evaluator/anim-clip.js (hunk 2 above)
Comment (ellthompson) [reply src/framework/anim/evaluator/anim-clip.js]: Moved this to a static class property.

File: src/framework/anim/evaluator/anim-clip.js [hunk 4]
```diff
@@ -104,35 +114,98 @@ class AnimClip {
...
+        if (this._eventCursor >= this.track.events.length) {
+            this._eventCursor = 0;
+        } else if (this._eventCursor < 0) {
+            this._eventCursor = this.track.events.length - 1;
         }
-        let clippedFrameDuration;
+    }
+
+    clipFrameTime(frameEndTime) {
+        AnimClip.eventFrame.start = 0;
```
Comment (mvaligursky) [inline src/framework/anim/evaluator/anim-clip.js:156]: just do `const eventFrame = AnimClip.eventFrame;` here

File: src/framework/anim/evaluator/anim-clip.js (hunk 3 above)
Comment (ellthompson) [reply src/framework/anim/evaluator/anim-clip.js]: The clip events are evaluated using an incoming delta time and the current speed. The clip's time will not necessarily have changed when this evaluation happens. That'll only occur if the user has actively set the time themselves.

**Review by mvaligursky — APPROVED** [review]
