### PR TITLE
Audio resume fix

### LINKED ISSUE #4760: Audio is blocked from playing on iOS if user starts with a swipe gesture since 1.56
Forum: https://forum.playcanvas.com/t/the-only-way-how-to-start-audio-on-ios-is-by-fast-tap-on-the-screen-no-swipe-or-touch-and-hold-anymore/27850

Using this project as the example: https://playcanvas.com/project/405821

https://launch.playcanvas.com/440098?debug=true&use_local_engine=https://code.playcanvas.com/playcanvas-1.56.0.js will start playing sound on a tap. However, if you swipe it will not play sound and subsequent taps will NOT start the sound.

https://launch.playcanvas.com/440098?debug=true&use_local_engine=https://code.playcanvas.com/playcanvas-1.55.4.js was the last working version.

This issue does not occur on Android

### PR DESCRIPTION
**Pull request by slimbuck**
Fixes #4760

iOS doesn't correctly resume on touchend event, but does on touchstart event.

This PR also simplifies manager suspend/resume logic a bit.

API Changes:
- removed SoundManager options object

### CODE REVIEW

File: src/platform/sound/manager.js [hunk 1]
```diff
@@ -46,52 +43,18 @@ class SoundManager extends EventHandler {
...
-
-        /**
-         * The function callback attached to the Window events USER_INPUT_EVENTS
-         *
-         * @type {EventListenerOrEventListenerObject}
-         * @private
-         */
-        this._resumeContextCallback = null;
+        // @ts-ignore
+        this.AudioContext = window.AudioContext || window.webkitAudioContext;
```
Comment (willeastcott) [inline src/platform/sound/manager.js:47]: You can't assume existence of `window` (e.g. when you're running in Node).

File: src/platform/sound/manager.js [hunk 2]
```diff
@@ -46,52 +43,18 @@ class SoundManager extends EventHandler {
...
-        this._forceWebAudioApi = options.forceWebAudioApi;
-
-        /**
-         * The function callback attached to the Window events USER_INPUT_EVENTS
-         *
-         * @type {EventListenerOrEventListenerObject}
-         * @private
-         */
-        this._resumeContextCallback = null;
+        // @ts-ignore
```
Comment (willeastcott) [inline src/platform/sound/manager.js:46]: I'd rather we disallowed `@ts-ignore` in the codebase. It appears nowhere else. There must be an alternative...

Comment (slimbuck) [reply src/platform/sound/manager.js]: Oh right, I'm so used to working in ts these days... removed.

File: src/platform/sound/manager.js [hunk 3]
```diff
@@ -125,87 +92,41 @@ class SoundManager extends EventHandler {
...
     destroy() {
-        this._removeUserInputListeners();
-
         this.fire('destroy');
 
-        if (this._context && this._context.close) {
-            this._context.close();
+        if (this._context) {
+            this._removeUnlockListeners();
+            this?._context?.close();
```
Comment (willeastcott) [inline src/platform/sound/manager.js:129]: But isn't `this._context` guaranteed to be valid by this point?

**Review by willeastcott — APPROVED** [review]

**Comment by willeastcott** [comment]
What about these lines:

https://github.com/playcanvas/engine/pull/4788/files#diff-bf489dbc39f80880f4921c574a985e18d6abd0c6716cd3d2907dbb96ed37e255R31-R32

That's public API:

https://developer.playcanvas.com/api/pc.SoundManager.html#SoundManager

So presumably this PR actually removes that option? I'm fine with that (to be honest, I'm not sure why anyone would want to use that option!). But if this is so, the docs should be updated.

File: src/platform/sound/manager.js (hunk 3 above)
Comment (slimbuck) [reply src/platform/sound/manager.js:129]: Not if AudioContext doesn't exist, like in engine tests :)

Comment (willeastcott) [reply src/platform/sound/manager.js:129]: I'm confused. Then the `if` condition would have failed, no?

Comment (slimbuck) [reply src/platform/sound/manager.js:129]: Oic you're referring to the first ? on this line. Yeah I can remove it. The old code tested for presence of context.close before invoking it, so the second ? should probably stay.

Comment (slimbuck) [reply src/platform/sound/manager.js]: Done, thanks!

**Comment by slimbuck** [comment]
> So presumably this PR actually removes that option? I'm fine with that (to be honest, I'm not sure why anyone would want to use that option!). But if this is so, the docs should be updated.

Oh yes, that code just didn't make any sense (and I assumed this was some legacy workaround). Perhaps I should investigate the origin of that option first and then decide whether to remove it entirely.

**Comment by willeastcott** [comment]
Sure, but also the whole options object from the code (plus passing it in application.js) since that was the only option. 😄

**Comment by slimbuck** [comment]
> Sure, but also the whole options object from the code (plus passing it in application.js) since that was the only option. 😄

Done!

**Comment by willeastcott** [comment]
OK, LGTM now. Nice job! 🙌

**Comment by willeastcott** [comment]
But maybe call out the API change in the PR description!

**Comment by slimbuck** [comment]
Thanks for your help @willeastcott !
