### PR TITLE
Fix `Entity#destroy`

### LINKED ISSUE #4649: Seemore double renders when destroying all the entities and loading the same scene hierarchy again
Related posts: https://github.com/playcanvas/engine/pull/4626#issuecomment-1249425411

image

Launch this project: https://playcanvas.com/project/983477/overview/f-seemore
Press 1

### PR DESCRIPTION
**Pull request by kungfooman**
Fixes #4649

The main issue is simply that `GraphNode` has no `destroy` method and if a `Entity` is inside a `GraphNode`... it will never be deleted.

I can imagine many solutions, but simply to get the conversations going I propose this one...

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by yaustar** [comment]
Just to confirm, that scene basically has:

```
entity
-> graph node
- -> entity
```

**Comment by kungfooman** [comment]
@yaustar yep exactly, testable like:

```js
const isEntityChildOfGraphNode = _ => _ instanceof pc.Entity && _.parent?.constructor === pc.GraphNode;
const entitiesInGraphNodes = pc.app.root.find(isEntityChildOfGraphNode);
entitiesInGraphNodes.map(ent => {
    const {name, path, parent} = ent;
    return {name, path, ent, parent};
});
```

Output in Seemore:

image


More ideas for (possible?) solutions:

1) As in PR, find these special cases before recursively destroy entities "normally" (as it always was)
2) Implement `GraphNode#destroy`?
3) Simply find every entity using `GraphNode#find` and delete them all iteratively?

Probably everything has pros/cons, but so far I tend to (1) or (2)

**Comment by mvaligursky** [comment]
personally I would find the `Implement GraphNode#destroy` option a lot cleaner, any reasons not to go that route?

**Comment by kungfooman** [comment]
I just thought about performance, lets say having 20 skeletons with ~70 `GraphNode`'s and `GraphNode` is a bit "lower level" and calling `destroy` on them even tho they may have no entities might be useless. But I guess in real-life people put entities in `GraphNode`'s all the time to track animated positions or attach particle effects, so being "pure" with GraphNode's is not really a thing.

> personally I would find the `Implement GraphNode#destroy` option a lot cleaner, any reasons not to go that route?

So I pretty much agree, I would also like to see `GraphNode#detachFromParent`, because I see it all over the place handled via nested if's:

image

Or other tricks are `GraphNode#reparent(null)`... which feels "okayish" once you know it, but still not 100% intuitive. I guess therefore it's only used once:

image

Would it be okay to implement `GraphNode#detachFromParent` and `GraphNode#destroy`?

**Comment by mvaligursky** [comment]
> Would it be okay to implement `GraphNode#detachFromParent` and `GraphNode#destroy`?

Absolutely, I'd like that. If possible, create two separate PRs please.

**Comment by kungfooman** [comment]
Debugging and debugging :nerd_face: 

image

Found another reason why it fails...

Called from:

image

Simply said, the "component removal code" is snatching away our entities (which we want to delete recursively) before our recursion ever has a chance to get to them (they just "disappear" 🤯👻💥).

This is easily fixed though, simply first disabled all component, then do the recursion, and then to component deletion.

Or 2nd possible solution: mark the entire hierarchy we want to delete (something like `_destroying` flag) beforehand and then make `GraphNode#removeChild` do nothing, because we know better (namely that this is not a removal but a destruction).

But I like the 1st solution, simply destroying the components after the recursion, so I will research that route a bit more... I realize that historically this stuff was a mine field, a change here breaks a project there etc... please just link me all scenes I shall test this with :mag: (after all, we want to fix bugs, not introduce new ones).

**Comment by kungfooman** [comment]
Ready for review... pretty happy about the result.

I'm testing with Seemore and besides the event bug I also found a room-loading bug in `demo-loader.js`:

https://github.com/kungfooman/seemore/commit/25e565c87a68721f2327e6e9632acc69d3748197

File: src/scene/graph-node.js [hunk 1]
```diff
@@ -480,6 +480,37 @@ class GraphNode extends EventHandler {
         return this;
     }
 
+
+    /**
+     * Detach it from the hierarchy. Then recursively destroy all ancestors.
```
Comment (mvaligursky) [inline src/scene/graph-node.js:485]:
```suggestion
     * Detach a GraphNode from the hierarchy. Then recursively destroy all ancestors.
```

File: src/framework/entity.js [hunk 2]
```diff
@@ -514,34 +514,13 @@ class Entity extends GraphNode {
             this.c[name].enabled = false;
         }
 
+        super.destroy();
```
[the remark this answers is not in the document]
Comment (kungfooman) [reply src/framework/entity.js:517]: That doesn't work, this would be the result:

image

Reason I described here: https://github.com/playcanvas/engine/pull/5414#issuecomment-1599076644

The components think they can remove entities from the hierarchy without deleting them, so the get orphaned basically and the recursion doesn't find them any longer.

File: src/framework/scene-registry.js [hunk 3]
```diff
@@ -376,14 +376,16 @@ class SceneRegistry {
...
-                const child = rootChildren[0];
-                child.reparent(null);
-                child.destroy?.();
+            // Destroy all nodes on the app.root
+            const { children } = app.root;
+            while (children.length) {
+                children[0].destroy();
             }
-
+            Debug.assert(
```
Comment (mvaligursky) [inline src/framework/scene-registry.js:384]: I'm not very familia with the _entityIndex, but could this incorrectly fire if we have entities with GUID that are not added to the root?

Comment (mvaligursky) [reply src/framework/scene-registry.js:384]: I can imagine entities that are not under the root .. for example in some pool class, or just stored to be displayed occasionally.

Comment (kungfooman) [reply src/framework/scene-registry.js]: Yep, personally I just keep those entities parented and enable/disable when needed, but yes, I can see how that's a possibility.

**Comment by kungfooman** [comment]
Context for latest commit:

image

Output of this code in `src/framework/components/model/component.js`:

```js
            this.removeModelFromLayers();
            const ents = this._model.getGraph().find(_ => _ instanceof Entity);
            if (ents.length) {
                console.log(ents);
            }
            this._model.getGraph().destroy();
```

**Review by mvaligursky — APPROVED** [review]
Approving, looks great to me, I don't see any problems now. Thanks!

File: src/framework/scene-registry.js [hunk 4]
```diff
@@ -376,14 +376,11 @@ class SceneRegistry {
...
 
         const onBeforeAddHierarchy = (sceneItem) => {
-            // Destroy/Remove all nodes on the app.root
-            const rootChildren = app.root.children;
-            while (rootChildren.length > 0) {
-                const child = rootChildren[0];
-                child.reparent(null);
-                child.destroy?.();
+            // Destroy all nodes on the app.root
+            const { children } = app.root;
```
Comment (willeastcott) [inline src/framework/scene-registry.js:380]: Why not just:

```
const children = app.root.children;
```

File: src/scene/graph-node.js [hunk 5]
```diff
@@ -480,6 +480,37 @@ class GraphNode extends EventHandler {
         return this;
     }
 
+
+    /**
+     * Detach a GraphNode from the hierarchy. Then recursively destroy all ancestors.
```
Comment (willeastcott) [inline src/scene/graph-node.js:485]: Shouldn't this say descendants instead of ancestors?

Comment (kungfooman) [reply src/scene/graph-node.js:485]: Wow, totally, thank you for seeing that! It's the original comment from here: https://github.com/playcanvas/engine/blob/039da2e23ca4a6dcc71630e5f3e79afe21553001/src/framework/entity.js#L502-L503

Do you want to make a code suggestion? "recursively destroy all children"?

Comment (willeastcott) [inline src/scene/graph-node.js:485]:
```suggestion
     * Detach a GraphNode from the hierarchy and recursively destroy all children.
```

**Review by willeastcott — APPROVED** [review]
