### PR TITLE
assignAnimation speed was not passed to new AnimState constructor

### LINKED ISSUE #5314: assignAnimation() speed is not always applied correctly when animating
Forum: https://forum.playcanvas.com/t/how-to-set-anim-state-speed/31184

Repro project: https://playcanvas.com/project/1073801/overview/f-animation-by-script

Editor setup:

image

Repro steps:
1. Launch scene
2. Press 3 to run t3 animation, that works fine
3. Press 2 to run t2 animation, it doesn't animate

However, if we only have the t2 animation in the editor setup, it works fine.

### PR DESCRIPTION
**Pull request by yaustar**
Fixes #5314

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by yaustar** [comment]
@ellthompson Can you see any knock ons for this fix in the rest of the anim system?

File: src/framework/anim/controller/anim-controller.js [hunk 1]
```diff
@@ -450,7 +450,7 @@ class AnimController {
         const path = pathString.split('.');
         let state = this._findState(path[0]);
         if (!state) {
-            state = new AnimState(this, path[0], 1.0);
+            state = new AnimState(this, path[0], speed);
```
Comment (yaustar) [inline src/framework/anim/controller/anim-controller.js:453]: See constructor for AnimState https://github.com/playcanvas/engine/blob/8fd5a033065fb4dfcd0fad4b1ecbdf25591e0f45/src/framework/anim/controller/anim-state.js#L40

**Review by ellthompson — APPROVED** [review]
