### PR TITLE
[BREAKING] UI Scroll Views now work in XR

### LINKED ISSUE #3983: UI Scroll view doesn't work in VR - Can't scroll with the VR controllers
Example project: https://playcanvas.com/project/878556/overview/test-scroll-area-in-vr

Forum thread: https://forum.playcanvas.com/t/scrollbar-not-working-in-vr/24047

### PR DESCRIPTION
**Pull request by yaustar**
Fixes #3983

Tested in AR and VR with these projects that already have the PR engine build in them:
- https://playcanvas.com/project/1021298/overview/f-webxr-ui-interaction
- https://playcanvas.com/project/1020950/overview/vr-scrolling-elements

https://user-images.githubusercontent.com/16639049/208667064-2c011316-0f4b-4604-a2f3-5ad8b18abb80.mp4

Breaking change: The `selectend` XR input event for elements has changed to work like `touchend` where it fires the event on the element that it was originally pressed on rather than the element that it is currently on.

I believe this will affect a very small number of users as typically they would either use `click` event to know if a button has been pressed or `selectstart` if they wanted an immediately response.

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by mvaligursky** [comment]
If this is [Breaking], it'd be good to have some more details of the breaking change in the description.

**Comment by yaustar** [comment]
@mvaligursky I started the PR but hit post to early 😅  

Breaking change added to the description

File: src/framework/components/element/element-drag-helper.js [hunk 1]
```diff
@@ -140,16 +145,20 @@ class ElementDragHelper extends EventHandler {
...
-        this._chooseRayOriginAndDirection();
+        if (event.inputSource) {
+            _ray.set(event.inputSource.getOrigin(), event.inputSource.getDirection());
+        } else {
+            this._determineInputPosition(event);
+            this._chooseRayOriginAndDirection();
+        }
 
-        _plane.point.copy(this._element.entity.getLocalPosition());
+        _plane.point.copy(this._element.entity.getPosition());
```
Comment (yaustar) [inline src/framework/components/element/element-drag-helper.js:161]: May need to revert or resolve a conflict as this was added in https://github.com/playcanvas/engine/pull/4935

File: src/framework/components/element/element-drag-helper.js [hunk 2]
```diff
@@ -215,7 +224,7 @@ class ElementDragHelper extends EventHandler {
 
         dragScale.x = 1 / dragScale.x;
         dragScale.y = 1 / dragScale.y;
-        dragScale.z = 1 / dragScale.z;
+        dragScale.z = 0;
```
Comment (yaustar) [inline src/framework/components/element/element-drag-helper.js:227]: This is currently in PR https://github.com/playcanvas/engine/pull/4937

File: src/framework/input/element-input.js [hunk 3]
```diff
@@ -837,21 +837,29 @@ class ElementInput {
             if (hoveredNow) this._fireEvent('selectenter', new ElementSelectEvent(event, hoveredNow, camera, inputSource));
         }
 
+        const pressed = this._selectedPressedElements[inputSource.id];
+        if (eventType === 'selectmove' && pressed) {
+            this._fireEvent('selectmove', new ElementSelectEvent(event, pressed, camera, inputSource));
+        }
```
Comment (yaustar) [inline src/framework/input/element-input.js:843]: This works like the touchmove event where it only fires on the element that it was originally clicked on

**Comment by yaustar** [comment]
@Maksims It would be great to get your review too as you originally wrote a lot of this :)

File: src/framework/input/element-input.js [hunk 4]
```diff
@@ -837,21 +837,29 @@ class ElementInput {
...
             if (hoveredNow) this._fireEvent('selectstart', new ElementSelectEvent(event, hoveredNow, camera, inputSource));
         }
 
-        const pressed = this._selectedPressedElements[inputSource.id];
         if (!inputSource.elementInput && pressed) {
             delete this._selectedPressedElements[inputSource.id];
-            if (hoveredBefore) this._fireEvent('selectend', new ElementSelectEvent(event, hoveredBefore, camera, inputSource));
+            if (hoveredBefore) {
+                this._fireEvent('selectend', new ElementSelectEvent(event, pressed, camera, inputSource));
+            }
```
Comment (yaustar) [inline src/framework/input/element-input.js:854]: Breaking change as this changes which element `selectend` is fired on.

I could make this non-breaking by changing the way this works more like the mouse where it fires the `mouseup` event on the current element if `mousedown` was not done on an element. And if it was, `mouseup` would fire on the element that was originally clicked on.

File: src/framework/input/element-input.js (hunk 3 above)
Comment (yaustar) [reply src/framework/input/element-input.js:843]: Question here is if I should make this more like the mouse where `selectmove` is fired on the current element that it is over unless it was clicked on an existing element to start with, in which case, it would do the above.

File: src/framework/components/element/element-drag-helper.js (hunk 2 above)
Comment (mvaligursky) [reply src/framework/components/element/element-drag-helper.js]: merge that change it and resolve the comment if no longer relevant

**Review by mvaligursky — APPROVED** [review]
