### PR TITLE
[FIX] Fix WebXR stereo frustum culling

### LINKED ISSUE #5787: WebXR Frustum Culling - Issue
Current WebXR Frustum Culling in multi-view session constructs Frustrum from the left view, which leads to early culling on the right edge of the right view.

We need to construct combined Frustrum from both view projections.

### PR DESCRIPTION
**Pull request by willeastcott**
## Summary
- Fix incorrect frustum culling in WebXR stereo rendering that caused objects on the right edge of the right eye to be culled early
- Add `Frustum.add()` method to combine frustums by keeping the outermost plane for each boundary

## Details
The previous implementation used only the first view's (left eye) frustum for culling, causing objects visible in the right eye but outside the left eye's view to be incorrectly culled.

The fix computes a combined frustum that encompasses all XR views by selecting the plane with the largest distance for each of the 6 frustum boundaries (left, right, top, bottom, near, far).

### Why this works for WebXR
This approach assumes frustums have parallel orientation (same plane normals). This is valid for WebXR stereo rendering because modern VR/AR headsets use **parallel projection** - both eyes look in the same direction with only a horizontal IPD offset, not toe-in convergence. With parallel views, frustum plane normals are identical and only distances differ, making plane merging by distance comparison correct.

### Public API Addition
```js
// Frustum.add(other) - expands frustum to contain another
frustumA.add(frustumB);
```

Fixes #5787
Closes #7411

## Checklist
- [x] I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md)
- [x] My code follows the project's coding standards
- [x] This PR focuses on a single change

### CODE REVIEW

File: src/core/shape/frustum.js [hunk 1]
```diff
@@ -111,6 +111,30 @@ class Frustum {
...
+     * objects visible in any view.
+     *
+     * Note: This method assumes both frustums have similar orientation (parallel views). This is
+     * valid for WebXR stereo rendering where eyes use parallel projection with only a horizontal
+     * offset, not toe-in convergence.
+     *
+     * @param {Frustum} other - The other frustum to add.
+     * @returns {Frustum} Self for chaining.
+     */
+    add(other) {
```
Comment (Maksims) [inline src/core/shape/frustum.js:127]: Such a simple solution, I did not think about.

**Comment by Maksims** [comment]
Tested on Quest 3 - works flawlessly.

Way to test: 
1. Open in VR this link: https://playcanvas.vercel.app/#/xr/xr-hands
2. Move your hand to top right corner, so boxes of joints start to be out of frame, and they will be culled too early.

And test from this PR (https://engine-nihpvle3p-playcanvas.vercel.app/#/xr/xr-hands) works well - early culling is gone.
