### PR TITLE
[AnimComponent] Fix for layer masks in cloned components

### LINKED ISSUE #4031: Instantiating a template with a layer mask in Anim doesn't apply the mask
Forum post: https://forum.playcanvas.com/t/entities-instantiated-from-templates-are-missing-their-anim-layer-masks/24330

Example project: https://playcanvas.com/project/883797/overview/layer-mask-clone-bug

Only happens when calling instantiate from code. Creating a new instance of the template in the Editor is fine.

### PR DESCRIPTION
**Pull request by ellthompson**
If an anim component is getting cloned and it is animating from the components own entity, we should be mapping all layer mask paths to start from the cloned entity rather than the old entity.

Fixes #4031 

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

File: src/framework/components/anim/system.js [hunk 1]
```diff
@@ -89,6 +89,22 @@ class AnimComponentSystem extends ComponentSystem {
     }
 
     cloneComponent(entity, clone) {
+        let masks;
```
Comment (mvaligursky) [inline src/framework/components/anim/system.js:92]: looks good, but this not take place even when the rootBone is specified? It can point to the root of the hierarchy in which case it's the same case?
I also wonder if we should in debug mode validate those paths against the hierarchy? Or does it take place when binding takes place? To make sure it's compatible skeleton.

Comment (ellthompson) [reply src/framework/components/anim/system.js:92]: Yeah, I was thinking that the rootBone would be null in that case (it is on the editor side). That should probably be replicated in the engine logic (assigning the components entity as the rootBone should result in a null rootBone).

The debugging would need to occur in the binder.

Comment (mvaligursky) [reply src/framework/components/anim/system.js:92]: I think it would not be null if the user assigned root entity to it?

Comment (ellthompson) [reply src/framework/components/anim/system.js:92]: Perhaps we should null the rootBone property if the components entity is assigned to it? To mirror the editor logic of entity assignments? Or we do a check for the component's entity as the rootBone here.

Comment (mvaligursky) [reply src/framework/components/anim/system.js:92]: I'd prefer we don't change the rootBone assignment .. if user assigns something, it should stay assigned, even if it's the same as the default case.

Comment (ellthompson) [reply src/framework/components/anim/system.js:92]: Ok i've updated this check to include the current entity.

File: src/framework/components/anim/system.js [hunk 2]
```diff
@@ -89,6 +89,22 @@ class AnimComponentSystem extends ComponentSystem {
...
+        // If the component animaites from the components entity, any layer mask hierarchy should be updated from the old entity to the cloned entity.
+        if (!entity.anim.rootBone || entity.anim.rootBone === entity) {
+            masks = {};
+            entity.anim.layers.forEach((layer, i) => {
+                if (layer.mask) {
+                    const mask = {};
+                    Object.keys(layer.mask).forEach((path) => {
+                        // The base of all mask paths should be mapped from the previous entity to the cloned entity
+                        const clonePath = path.replace(path.split('/')[0], clone.name);
```
Comment (mvaligursky) [inline src/framework/components/anim/system.js:101]: could you also improve this line to make sure it only renames the first segment of the path (that's what needs to happen right?) .. for example replacing `root` by `clone` in `/root/rooter/something' would not give us expected result.

**Review by mvaligursky — APPROVED** [review]
