### PR TITLE
[Animation] Binding updates and bug fixes

### LINKED ISSUE #2751: Since 1.38.0, Anim state graph transitions duration are not respected. Transitions are instant
Example project: https://playcanvas.com/editor/scene/995061

There's a blend between animations on engine 1.37.1 https://launch.playcanvas.com/995061?debug=true&use_local_engine=https://code.playcanvas.com/playcanvas-1.37.1.js

But are instant on 1.38.3: https://launch.playcanvas.com/995061?debug=true

### LINKED ISSUE #2771: [AnimComponent] Support rebinding animation curves
There will be times when a user may want to swap out an entities model for a new one while maintaining the current animation state of that entity. This would require that current animation curves in the AnimEvaluator are rebound to the new hierarchy. 

A typical use case for this would be a character customisation screen where an entities animation must be maintained while it's model is constantly updated.

### LINKED ISSUE #2786: Issue with assignAnimation method of AnimController class
`assignAnimation` of `AnimController` passes `path` array to `state.addAnimation` instead of an actual path string:

https://github.com/playcanvas/engine/blob/cb4d0ddb59da9616e8d54d0a1007cebcf35cff5a/src/anim/controller/anim-controller.js#L417

It should probably pass `path[0]` instead.

This causses an issue when trying to override animation for a specific state as this condition will never be met:

https://github.com/playcanvas/engine/blob/6fe0240780b50b0a7fc5c9b1f8927e2718dc1a2a/src/anim/controller/anim-state.js#L45

P.S. This seems like a situation where using Typescript would prove useful :)

### LINKED ISSUE #2788: pc.AnimComponent#removeNodeAnimations wrong jsdoc
Name tag should be `removeNodeAnimations` instead of  `removeStateAnimations`:

https://github.com/playcanvas/engine/blob/cb4d0ddb59da9616e8d54d0a1007cebcf35cff5a/src/framework/components/anim/component.js#L217

### PR DESCRIPTION
**Pull request by ellthompson**
- Adds the rebind function to the anim component and component layers to allow for any currently playing animations to rebind using current entity properties.
- Uses absolute scene paths when storing AnimTargets in the AnimEvaluator to ensure the correct blending and assignment of animations even when animation curve paths mismatch the scene structure.
- Fixes jsdocs for the AnimComponent
- Fixes the AnimState.addAnimation function to overwrite existing animations when the same path is used

**New API:**
```javascript
// Rebind any animations in the layer to the currently present components and model of the anim components entity
pc.AnimComponentLayer#rebind: function ();
// Rebind all of the components layers
pc.AnimComponent#rebind: function ();
```

Fixes #2771 
Fixes #2751
Fixes #2788
Fixes #2786

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

File: src/anim/binder/default-anim-binder.js [hunk 1]
```diff
@@ -56,23 +56,38 @@ class DefaultAnimBinder {
                 var func = function (value) {
                     object.set.apply(object, value);
                 };
-                return new AnimTarget(func, 'vector', 3);
+                var targetIdentifier = AnimBinder.encode({
+                    entityPath: node.path,
+                    component: 'entity',
+                    propertyPath: 'localPosition'
+                });
+                return new AnimTarget(func, 'vector', 3, targetIdentifier);
```
Comment (mvaligursky) [inline src/anim/binder/default-anim-binder.js:64]: these get repeated bellow few times .. perhaps wrap it in a function?

File: src/anim/evaluator/anim-evaluator.js [hunk 2]
```diff
@@ -238,6 +236,16 @@ class AnimEvaluator {
         return null;
     }
 
+    rebind() {
+        this._binder.rebind();
+        this._targets = {};
+        var clips = [...this.clips];
```
Comment (mvaligursky) [inline src/anim/evaluator/anim-evaluator.js:242]: please make sure this transpiles to something acceptable in es5 .. I don't think we've tested it yet.

File: src/framework/components/anim/component-binder.js [hunk 3]
```diff
@@ -87,16 +100,37 @@ class AnimComponentBinder extends DefaultAnimBinder {
                 if (!propertyComponent) {
                     var entityPath = AnimBinder.splitPath(propertyLocation.entityPath[0], '/');
                     propertyComponent = this.nodes[entityPath[entityPath.length - 1] || ""];
+
+                    // #ifdef DEBUG
+                    var fallbackGraphPath = (entityPath[entityPath.length - 1] || "") + '/' + propertyLocation.propertyPath;
+                    if (this._visitedFallbackGraphPaths[fallbackGraphPath]) {
+                        console.warn('Multiple nodes with the path ' + fallbackGraphPath + ' are present in the entities graph which may result in the incorrect binding of animations');
```
Comment (mvaligursky) [inline src/framework/components/anim/component-binder.js:107]: if you can easily print the name of the entity the anim component is on, that would be useful as well

File: src/anim/evaluator/anim-evaluator.js (hunk 2 above)
Comment (ellthompson) [reply src/anim/evaluator/anim-evaluator.js:242]: Yep i've tested this using `rollup -c --watch --environment target:es5`

File: src/framework/components/anim/component-binder.js (hunk 3 above)
Comment (ellthompson) [reply src/framework/components/anim/component-binder.js:107]: Sure i'll add that in

File: src/anim/binder/default-anim-binder.js (hunk 1 above)
Comment (ellthompson) [reply src/anim/binder/default-anim-binder.js:64]: 👍

File: src/anim/binder/default-anim-binder.js [hunk 4]
```diff
@@ -124,28 +128,48 @@ class DefaultAnimBinder {
...
+        return node;
+    }
+
+    static createAnimTarget(func, type, valueCount, node, propertyPath, componentType) {
+        var targetPath = AnimBinder.encode(node.path, componentType ? componentType : 'entity', propertyPath);
+        return new AnimTarget(func, type, valueCount, targetPath);
+    }
+
+    resolve(path) {
+        var target = this.targetCache[AnimBinder.encode(path.entityPath, path.component, path.propertyPath)];
```
Comment (slimbuck) [inline src/anim/binder/default-anim-binder.js:153]: you can cache the `encode` result here and reuse it down below.

File: src/anim/binder/anim-binder.js [hunk 5]
```diff
@@ -51,41 +51,22 @@ class AnimBinder {
...
-    static decode(locator) {
-        var locatorSections = AnimBinder.splitPath(locator, '/');
-        return {
-            entityPath: AnimBinder.splitPath(locatorSections[0]),
-            component: locatorSections[1],
-            propertyPath: AnimBinder.splitPath(locatorSections[2])
-        };
+    static encode(entityPath, component, propertyPath) {
+        return `${
+            Array.isArray(entityPath) ? AnimBinder.joinPath(entityPath) : entityPath
```
Comment (slimbuck) [inline src/anim/binder/anim-binder.js:66]: we no longer have need to decode paths that were previously encoded (right?). The purpose of this encode function is to create a unique key for the given path. In this  case we don't need to be careful with escaping characters etc. So presumably `AnimBinder.joinPath` (with fancy regex etc) can be removed and this call can be replaced with a simple `array.join('/')`?

File: src/framework/components/anim/component-binder.js [hunk 6]
```diff
@@ -67,36 +67,50 @@ class AnimComponentBinder extends DefaultAnimBinder {
     }
 
     resolve(path) {
-        var propertyLocation = AnimBinder.decode(path);
-
-        var entity = this._getEntityFromHierarchy(propertyLocation.entityPath);
-
-        if (!entity)
-            return null;
+        var target = this.targetCache[AnimBinder.encode(path.entityPath, path.component, path.propertyPath)];
```
Comment (slimbuck) [inline src/framework/components/anim/component-binder.js:70]: ditto here, cache `encode` result here and use it in one of the cases below

File: src/anim/binder/default-anim-binder.js [hunk 7]
```diff
@@ -124,28 +128,48 @@ class DefaultAnimBinder {
         };
     }
 
-    resolve(path) {
-        var propertyLocation = AnimBinder.decode(path);
-
-        var node = this.graph.findByPath(propertyLocation.entityPath[0]);
+    findNode(graph, path) {
+        var node = graph.findByPath(path.entityPath.join('/'));
```
Comment (slimbuck) [inline src/anim/binder/default-anim-binder.js:132]: it might be worth adding a `findByPath` function to graph-node which takes the array and uses it directly instead of joining into a string here (which won't handle escapes properly) just to split in the function. @willeastcott would you be ok adding a function to `GraphNode` or so we keep such a function here in `default-anim-binder`?

Comment (ellthompson) [reply src/anim/binder/default-anim-binder.js]: I've updated the graph.findByPath function to support arrays too.

File: src/framework/components/anim/component-binder.js (hunk 6 above)
Comment (ellthompson) [reply src/framework/components/anim/component-binder.js]: 👍

File: src/anim/binder/anim-binder.js (hunk 5 above)
Comment (ellthompson) [reply src/anim/binder/anim-binder.js]: Cheers, updated 👍

File: src/framework/components/anim/component-binder.js [hunk 8]
```diff
@@ -67,36 +67,51 @@ class AnimComponentBinder extends DefaultAnimBinder {
...
             case 'graph':
-                if (entity.model && entity.model.model && entity.model.model.graph) {
-                    propertyComponent = entity.model.model.graph.findByPath(propertyLocation.entityPath[0]);
-                }
-                if (!propertyComponent) {
-                    var entityPath = AnimBinder.splitPath(propertyLocation.entityPath[0], '/');
-                    propertyComponent = this.nodes[entityPath[entityPath.length - 1] || ""];
-                }
+                entity = this.animComponent.entity;
+                var graph = entity.model && entity.model.model && entity.model.model.graph;
```
Comment (willeastcott) [inline src/framework/components/anim/component-binder.js:90]: You could potentially use optional chaining here:

```javascript
                var graph = entity.model?.model?.graph;
```

File: src/framework/components/anim/component-binder.js [hunk 9]
```diff
@@ -67,36 +67,51 @@ class AnimComponentBinder extends DefaultAnimBinder {
...
+                propertyComponent = this.findNode(graph, path);
```
Comment (willeastcott) [inline src/framework/components/anim/component-binder.js:91]: Should you be checking that `graph` is valid before doing a `findNode` op?

File: src/framework/components/anim/component-binder.js [hunk 10]
```diff
@@ -240,10 +255,31 @@ class AnimComponentBinder extends DefaultAnimBinder {
...
+        return new AnimTarget(setter, animDataType, animDataComponents, targetPath);
+    }
+
+    rebind() {
+        this.targetCache = {};
+        // #ifdef DEBUG
+        this.visitedFallbackGraphPaths = {};
+        // #endif
+        var entity = this.animComponent && this.animComponent.entity;
+        var graph = entity.model && entity.model.model && entity.model.model.graph;
```
Comment (willeastcott) [inline src/framework/components/anim/component-binder.js:270]: Again, you could potentially use [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) here:

```javascript
                var graph = entity.model?.model?.graph;
```

Comment (willeastcott) [reply src/framework/components/anim/component-binder.js:270]: Although I'm a bit confused about the logic here. The code checks there's an `animComponent` property without assuming it's existence. Which indicates maybe `entity` could end up as `undefined`. But `entity` is assumed to be defined on the following line.

**Review by willeastcott — APPROVED** [review]
Approving with a few minor comments.

File: src/framework/components/anim/component-binder.js (hunk 8 above)
Comment (mvaligursky) [reply src/framework/components/anim/component-binder.js:90]: I see this handles entity.model ... and I hope there's handling of entity.render as well for the new render component?

**Comment by mvaligursky** [comment]
Please make sure render component is supported in addition to a model component.

**Comment by ellthompson** [comment]
> Please make sure render component is supported in addition to a model component.

I've tested this and it's working.

File: src/framework/components/anim/component-binder.js (hunk 9 above)
Comment (ellthompson) [reply src/framework/components/anim/component-binder.js]: I've removed this now. The findNode function now uses the graph class property.

File: src/framework/components/anim/component-binder.js (hunk 8 above)
Comment (ellthompson) [reply src/framework/components/anim/component-binder.js]: I've made this more generic so it'll use the entity as the base of the graph when no model component is present, tested and working 👍

File: src/framework/components/anim/component-binder.js (hunk 10 above)
Comment (ellthompson) [reply src/framework/components/anim/component-binder.js]: Yeah I didn't need to check animComponent here as it's always always available to the class. I've updated this to use conditional chaining too.

File: src/framework/components/anim/component-binder.js [hunk 11]
```diff
@@ -240,10 +253,32 @@ class AnimComponentBinder extends DefaultAnimBinder {
...
+    }
+
+    rebind() {
+        this.targetCache = {};
+        // #ifdef DEBUG
+        this.visitedFallbackGraphPaths = {};
+        // #endif
+
+        if (this.animComponent.entity.model?.model?.graph) {
+            this.graph = this.animComponent.entity.model?.model?.graph;
```
Comment (mvaligursky) [inline src/framework/components/anim/component-binder.js:269]: just double checking that this works for render component as well .. is this.graph set to this.entity or similar somewhere?

**Review by mvaligursky — APPROVED** [review]
approving with one comment

File: src/framework/components/anim/component-binder.js (hunk 11 above)
Comment (ellthompson) [reply src/framework/components/anim/component-binder.js:269]: Yep, if a model component isn't present it'll always use the current entity as the root of the graph.
