### PR TITLE
Changed collision checks to properly check on each each internal physics world time step.

### LINKED ISSUE #2072: [Physics] Collision Checking Incorrect
Related forum posts:
[Events not firing properly when increasing fixedtimestep](https://forum.playcanvas.com/t/collision-events-not-firing-properly-when-increasing-fixedtimestep/6241)
[Ammo js not returning collision callbacks](https://forum.playcanvas.com/t/solved-ammo-js-not-returning-collision-callbacks/7064)

The update function in the Rigidbody system file is checking for collisions after stepSimulation is called, but collisions can occur and then stop occurring during a single stepSimulation called if either 

a. The frame rate is low 
b. You decrease the fixedTimeStep to increase simulation accuracy (for example to 1 / 120) 

The easiest way to reproduce this is to increase the fixedTimeStep to something small like 1 / 240 and log collision events, it's clearly noticeable that many collision events are not being fired. 

This is because the stepSimulation will take how many ever substeps in increments of the fixedTimeStep it needs to in order to fill the deltaTime you pass it. So if you are using the dispatcher and the manifolds to check for collisions, if a collision occurs during one of these substeps but then is not occurring at the last substep then Playcanvas will fail to fire a collision event. 

Bullet has a built in method for handling this that is exposed in Ammo as dynamicsWorld.setInternalTickCallback. This will allow you to register a callback (the separated checkCollision function) that fires on each actual simulation step. This is what this looks like. I've tested all of the following code and it fixes the issue. If you'd like a pull request for this stuff let me know. 

```
var callback = Ammo.addFunction(this.checkForCollisions.bind(this), 'vif');
this.dynamicsWorld.setInternalTickCallback(callback);
```

The code for collision checking would then be removed from the update function as follows

```
// onUpdate(dt) function in the rigid-body/system.js

// #ifdef PROFILER
this._stats.physicsStart = pc.now();
// #endif

// Check to see whether we need to update gravity on the dynamics world
var gravity = this.dynamicsWorld.getGravity();
if (
  gravity.x() !== this.gravity.x ||
  gravity.y() !== this.gravity.y ||
  gravity.z() !== this.gravity.z
) {
  gravity.setValue(this.gravity.x, this.gravity.y, this.gravity.z);
  this.dynamicsWorld.setGravity(gravity);
}

// Update the transforms of all bodies
this.dynamicsWorld.stepSimulation(dt, this.maxSubSteps, this.fixedTimeStep);

// Update the transforms of all entities referencing a body
var components = this.store;
for (var id in components) {
  if (components.hasOwnProperty(id)) {
    var entity = components[id].entity;
    var componentData = components[id].data;
    if (
      componentData.body &&
      componentData.body.isActive() &&
      componentData.enabled &&
      entity.enabled
    ) {
      if (componentData.type === pc.BODYTYPE_DYNAMIC) {
        entity.rigidbody.syncBodyToEntity();
      } else if (componentData.type === pc.BODYTYPE_KINEMATIC) {
        entity.rigidbody._updateKinematic(dt);
      }
    }
  }
}

// #ifdef PROFILER
this._stats.physicsTime = pc.now() - this._stats.physicsStart;
// #endif

```

New check for collisions function 

```
      checkForCollisions: function (dw, timestep) {
        // Check for collisions and fire callbacks
        var dispatcher = this.dynamicsWorld.getDispatcher();
        var numManifolds = dispatcher.getNumManifolds();
        var i, j;

        frameCollisions = {};

        // loop through the all contacts and fire events
        for (i = 0; i < numManifolds; i++) {
          var manifold = dispatcher.getManifoldByIndexInternal(i);

          var body0 = manifold.getBody0();
          var body1 = manifold.getBody1();

          var wb0 = Ammo.castObject(body0, Ammo.btRigidBody);
          var wb1 = Ammo.castObject(body1, Ammo.btRigidBody);

          var e0 = wb0.entity;
          var e1 = wb1.entity;

          // check if entity is null - TODO: investigate when this happens
          if (!e0 || !e1) {
            continue;
          }

          var flags0 = wb0.getCollisionFlags();
          var flags1 = wb1.getCollisionFlags();

          var numContacts = manifold.getNumContacts();
          var forwardContacts = [];
          var reverseContacts = [];
          var newCollision, e0Events, e1Events, e0BodyEvents, e1BodyEvents;

          if (numContacts > 0) {
            // don't fire contact events for triggers
            if (
              flags0 & pc.BODYFLAG_NORESPONSE_OBJECT ||
              flags1 & pc.BODYFLAG_NORESPONSE_OBJECT
            ) {
              e0Events =
                e0.collision &&
                (e0.collision.hasEvent("triggerenter") ||
                  e0.collision.hasEvent("triggerleave"));
              e1Events =
                e1.collision &&
                (e1.collision.hasEvent("triggerenter") ||
                  e1.collision.hasEvent("triggerleave"));
              e0BodyEvents =
                e0.rigidbody &&
                (e0.rigidbody.hasEvent("triggerenter") ||
                  e0.rigidbody.hasEvent("triggerleave"));
              e1BodyEvents =
                e1.rigidbody &&
                (e1.rigidbody.hasEvent("triggerenter") ||
                  e1.rigidbody.hasEvent("triggerleave"));

              // fire triggerenter events for triggers
              if (e0Events) {
                newCollision = this._storeCollision(e0, e1);
                if (newCollision && !(flags1 & pc.BODYFLAG_NORESPONSE_OBJECT)) {
                  e0.collision.fire("triggerenter", e1);
                }
              }

              if (e1Events) {
                newCollision = this._storeCollision(e1, e0);
                if (newCollision && !(flags0 & pc.BODYFLAG_NORESPONSE_OBJECT)) {
                  e1.collision.fire("triggerenter", e0);
                }
              }

              // fire triggerenter events for rigidbodies
              if (e0BodyEvents) {
                if (!newCollision) {
                  newCollision = this._storeCollision(e1, e0);
                }

                if (newCollision) {
                  e0.rigidbody.fire("triggerenter", e1);
                }
              }

              if (e1BodyEvents) {
                if (!newCollision) {
                  newCollision = this._storeCollision(e0, e1);
                }

                if (newCollision) {
                  e1.rigidbody.fire("triggerenter", e0);
                }
              }
            } else {
              e0Events = this._hasContactEvent(e0);
              e1Events = this._hasContactEvent(e1);
              var globalEvents = this.hasEvent("contact");

              if (globalEvents || e0Events || e1Events) {
                for (j = 0; j < numContacts; j++) {
                  var btContactPoint = manifold.getContactPoint(j);

                  var contactPoint = this._createContactPointFromAmmo(
                    btContactPoint
                  );
                  var reverseContactPoint = null;
                  if (e0Events || e1Events) {
                    reverseContactPoint = this._createReverseContactPointFromAmmo(
                      btContactPoint
                    );
                    forwardContacts.push(contactPoint);
                    reverseContacts.push(reverseContactPoint);
                  }

                  if (globalEvents) {
                    // fire global contact event for every contact
                    var result = this._createSingleContactResult(
                      e0,
                      e1,
                      contactPoint
                    );
                    this.fire("contact", result);
                  }
                }

                if (e0Events) {
                  var forwardResult = this._createContactResult(
                    e1,
                    forwardContacts
                  );
                  newCollision = this._storeCollision(e0, e1);

                  if (e0.collision) {
                    e0.collision.fire("contact", forwardResult);
                    if (newCollision) {
                      e0.collision.fire("collisionstart", forwardResult);
                    }
                  }

                  if (e0.rigidbody) {
                    e0.rigidbody.fire("contact", forwardResult);
                    if (newCollision) {
                      e0.rigidbody.fire("collisionstart", forwardResult);
                    }
                  }
                }

                if (e1Events) {
                  var reverseResult = this._createContactResult(
                    e0,
                    reverseContacts
                  );
                  newCollision = this._storeCollision(e1, e0);

                  if (e1.collision) {
                    e1.collision.fire("contact", reverseResult);
                    if (newCollision) {
                      e1.collision.fire("collisionstart", reverseResult);
                    }
                  }

                  if (e1.rigidbody) {
                    e1.rigidbody.fire("contact", reverseResult);
                    if (newCollision) {
                      e1.rigidbody.fire("collisionstart", reverseResult);
                    }
                  }
                }
              }
            }
          }
        }
        this._cleanOldCollisions();

        // Reset contact pools
        this.contactPointPool.freeAll();
        this.contactResultPool.freeAll();
        this.singleContactResultPool.freeAll();
      },
```

### PR DESCRIPTION
**Pull request by maxbbb**
Fixes #2072 

Separates the check collision logic into its own function and lets Ammo handle calling it on each internal time step. Provides warning if user is using older version that does not support setInternalTickCallback and falls back to calling after each stepSimulation if unavailable. 

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

File: src/framework/components/rigid-body/system.js [hunk 1]
```diff
@@ -522,38 +529,16 @@ Object.assign(pc, function () {
...
-                }
-            }
-
+        /**
+         * @private
+         * @function
+         * @name pc.RigidBodyComponentSystem#_checkForCollisions
+         * @description Checks for collisions and fires collision events
+         * @param {pc.Entity} dynamicsWorld - The pointer to the dynamics world that invoked this callback.
+         * @param {pc.Entity} timeStep - The amount of simulation time processed in the last simulation tick.
```
Comment (willeastcott) [inline src/framework/components/rigid-body/system.js:538]: Type is wrong. Should be `number`.

File: src/framework/components/rigid-body/system.js [hunk 2]
```diff
@@ -522,38 +529,16 @@ Object.assign(pc, function () {
...
-
-                }
-            }
-
+        /**
+         * @private
+         * @function
+         * @name pc.RigidBodyComponentSystem#_checkForCollisions
+         * @description Checks for collisions and fires collision events
+         * @param {pc.Entity} dynamicsWorld - The pointer to the dynamics world that invoked this callback.
```
Comment (willeastcott) [inline src/framework/components/rigid-body/system.js:537]: Type is wrong. Should be `object`.

File: src/framework/components/rigid-body/system.js [hunk 3]
```diff
@@ -705,6 +690,42 @@ Object.assign(pc, function () {
...
+                        } else if (componentData.type === pc.BODYTYPE_KINEMATIC) {
+                            entity.rigidbody._updateKinematic(dt);
+                        }
+                    }
+
+                }
+            }
+
+            if (!this.dynamicsWorld.setInternalTickCallback)
+                this._checkForCollisions();
```
Comment (willeastcott) [inline src/framework/components/rigid-body/system.js:728]: Personally, I would pass `this.dynamicsWorld` and `dt` here, since that's the function signature now.

**Comment by Maksims** [comment]
From warning text:
> This version of ammo.js can potentially fail to report contacts.
Is this due to this change, it always been a case?

Does this change can break any existing projects in development?

Also, please put warning log, under "Debug" build ifdef. Spamming logs in release builds, are discouraged.

File: src/framework/components/rigid-body/system.js [hunk 4]
```diff
@@ -522,38 +529,16 @@ Object.assign(pc, function () {
...
+         * @function
+         * @name pc.RigidBodyComponentSystem#_checkForCollisions
+         * @description Checks for collisions and fires collision events
+         * @param {pc.Entity} dynamicsWorld - The pointer to the dynamics world that invoked this callback.
+         * @param {pc.Entity} timeStep - The amount of simulation time processed in the last simulation tick.
+         * @returns {void}
+         */
+        _checkForCollisions: function (dynamicsWorld, timeStep) {
             // Check for collisions and fire callbacks
             var dispatcher = this.dynamicsWorld.getDispatcher();
```
Comment (willeastcott) [inline src/framework/components/rigid-body/system.js:543]: I'd change `this.dynamicsWorld` to just `dynamicsWorld` since it's a parameter of the function now.

File: src/framework/components/rigid-body/system.js [hunk 5]
```diff
@@ -181,6 +181,13 @@ Object.assign(pc, function () {
                 var solver = new Ammo.btSequentialImpulseConstraintSolver();
                 this.dynamicsWorld = new Ammo.btDiscreteDynamicsWorld(dispatcher, overlappingPairCache, solver, collisionConfiguration);
 
+                if (this.dynamicsWorld.setInternalTickCallback) {
+                    var checkForCollisionsPointer = Ammo.addFunction(this._checkForCollisions.bind(this), 'vif');
+                    this.dynamicsWorld.setInternalTickCallback(checkForCollisionsPointer);
+                } else {
+                    console.warn("WARNING: This version of ammo.js can potentially fail to report contacts. Please update it to the latest version.");
```
Comment (willeastcott) [inline src/framework/components/rigid-body/system.js:188]: Wrap this with #ifdef DEBUG and #endif. For example: https://github.com/playcanvas/engine/blob/master/src/scene/graph-node.js#L1050

File: src/framework/components/rigid-body/system.js (hunk 2 above)
Comment (willeastcott) [reply src/framework/components/rigid-body/system.js:537]: Also, I would say 'The dynamics world that...` instead of `The pointer to the dynamics world...` since this is JavaScript rather than C++. 😄

**Comment by willeastcott** [comment]
No @Maksims, this doesn't break projects on older versions of ammo.js. And yep, I've logged a comment in my review about wrapping the warning with DEBUG define. 👍 

Thanks for the review!

File: src/framework/components/rigid-body/system.js (hunk 4 above)
Comment (maxbbb) [reply src/framework/components/rigid-body/system.js:543]: So because of the way WASM handles that callback, the dyanmicsWorld is returned at an integer pointer and you would have to make an extra call every step to get the underlying data which seems like it would have an impact on performance. They could be removed from the function signature and it will still work fine, but I figured in the future if you wanted to keep track of exact simulation time you would need the timeStep and would have to define the dynamicsWorld to get that.

File: src/framework/components/rigid-body/system.js (hunk 2 above)
Comment (maxbbb) [reply src/framework/components/rigid-body/system.js:537]: Given the point about the integer pointer, would @param {object | number} be appropriate here?

Comment (willeastcott) [reply src/framework/components/rigid-body/system.js:537]: Sounds like it should be `number` 😄

File: src/framework/components/rigid-body/system.js (hunk 4 above)
Comment (willeastcott) [reply src/framework/components/rigid-body/system.js:543]: Gotcha. OK, then let's leave this 'as is'.

File: src/framework/components/rigid-body/system.js (hunk 2 above)
Comment (maxbbb) [reply src/framework/components/rigid-body/system.js:537]: If it's passed in when this function is called from the update function for versions of Ammo that don't have setInternalTickCallback then it will be an object.

File: src/framework/components/rigid-body/system.js (hunk 3 above)
Comment (willeastcott) [reply src/framework/components/rigid-body/system.js:728]: OK, forget this since `this.dynamicWorld` does not equal the `number` value passed from ammo.js.

File: src/framework/components/rigid-body/system.js (hunk 5 above)
Comment (maxbbb) [reply src/framework/components/rigid-body/system.js:188]: If I do that the linter complains about the else statement not being on the same line as the closing bracket of the if statement 😞

Comment (maxbbb) [reply src/framework/components/rigid-body/system.js:189]: Linter didn't seem to have a problem with just wrapping the inside of the else. Pushed what should resolve the rest.

Comment (willeastcott) [reply src/framework/components/rigid-body/system.js:189]: How about:

```
if (this.dynamicsWorld.setInternalTickCallback) {
    var checkForCollisionsPointer = Ammo.addFunction(this._checkForCollisions.bind(this), 'vif');
    this.dynamicsWorld.setInternalTickCallback(checkForCollisionsPointer);
}

#ifdef DEBUG
if (!this.dynamicsWorld.setInternalTickCallback) {
    console.warn("WARNING: This version of ammo.js can potentially fail to report contacts. Please update it to the latest version.");
}
#endif
```

Comment (willeastcott) [reply src/framework/components/rigid-body/system.js:189]: Oh cool, sounds good.

**Comment by willeastcott** [comment]
Hey @maxbbb, I've updated this slightly based on what I was saying before about fixing the function signature of the callback:

https://github.com/playcanvas/engine/pull/1997/commits/3a42c0f5c11a8f151ea00c8ec7380cb8571cd9da

Seems to work fine. 😄

**Comment by maxbbb** [comment]
Yeah I can see for consistency why that would be the best approach. I haven't done any profiling on it so the performance difference might be incredibly small, but in an application where you decrease the fixedTimeStep to something like 1 / 240 that function is getting called a lot and I'm not sure of the cost of the wrapPointer function. I'll do some profiling and let you know.

**Comment by willeastcott** [comment]
I suspect that the cost of wrapping the pointer is tiny compared to the cost of executing the body of `_checkForCollisions`, even when there are no contacts to process.
