### PR TITLE
[Fix] Glb converts 32bit index buffer to 16 if device does not support it

### LINKED ISSUE #2157: GLB models/assets do not render on some older Android Devices
Example project: https://playcanvas.com/project/693898/overview/glb-android-bug

GT-I9500 (https://www.gsmarena.com/samsung_i9500_galaxy_s4-5125.php) renders fine. 
WebGL report
GT-I9500 native browser 2

SM-J320F (https://www.gsmarena.com/samsung_galaxy_j3_(2016)-7760.php) does not render:
SM-J320F 2

Neither device supports WebGL 2. No errors or logs in console.

### PR DESCRIPTION
**Pull request by mvaligursky**
Fixes #2157

### CODE REVIEW

File: src/resources/parser/glb-parser.js [hunk 1]
```diff
@@ -706,10 +706,25 @@ var createMesh = function (device, gltfMesh, accessors, bufferViews, callback, d
...
+
+                // #ifdef DEBUG
+                if (vertexBuffer.numVertices > 0xFFFF) {
+                    console.warn("Glb file contains 32bit index buffer but these are not supported by this device - it may be rendered incorrectly.");
+                }
+                // #endif
+
+                // convert to 16bit
+                indexFormat = INDEXFORMAT_UINT16;
+                var oldIndices = indices;
```
Comment (slimbuck) [inline src/resources/parser/glb-parser.js:723]: you can just do ```indices = new Uint16Array(indices);```

Comment (mvaligursky) [reply src/resources/parser/glb-parser.js]: nice! done.
