### PR TITLE
[FIX] Unhook asset event callbacks when destroying model component. 

### LINKED ISSUE #1138: app.destroy() material bug
Hi, if there is a playcanvas plane with a diffuse texture material, app.destroy() triggers a bug. Here is a simple example with destroy triggered by clicking anywhere on the screen: https://playcanvas.com/editor/scene/595955

### PR DESCRIPTION
**Pull request by willeastcott**
Fixes #1138.

### CODE REVIEW

File: src/framework/components/model/system.js [hunk 1]
```diff
@@ -143,6 +143,8 @@ pc.extend(pc, function () {
         },
 
         onRemove: function(entity, component) {
+            // Unhook any masterial asset events
```
Comment (vkalpias) [inline src/framework/components/model/system.js]: masterial?

Comment (willeastcott) [reply src/framework/components/model/system.js]: Whoops. Fixed.
