### PR TITLE
Fix WebXR AR quarter rendering issue

### LINKED ISSUE #3260: WebXR Image tracking project is clipping the render in AR mode
Forum: https://forum.playcanvas.com/t/webxr-ar-image-tracking-render-clipping/20797

You can only see a quarter of the 3D render on top of the camera view.

If device pixel ratio is disabled, only part of the screen renders the 3D scene.

### PR DESCRIPTION
**Pull request by yaustar**
Fixes #3260

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

File: src/framework/application.js [hunk 1]
```diff
@@ -1420,8 +1420,8 @@ class Application extends EventHandler {
      * events) so that the canvas resolution is immediately updated.
      */
     updateCanvasSize() {
-        // Don't update if we are in VR
-        if ((this.vr && this.vr.display) || (this.xr.active && this.xr.type === XRTYPE_VR)) {
+        // Don't update if we are in VR or XR
+        if ((!this._allowResize) || (this.xr.active)) {
```
Comment (yaustar) [inline src/framework/application.js:1424]: Matches logic for WebVR in resizeCanvas: https://github.com/playcanvas/engine/blob/e76b5faa9c5f34ba9a0dbde424596aaa2cfa6fd8/src/framework/application.js#L1376

File: src/xr/xr-plane-detection.js [hunk 2]
```diff
@@ -74,9 +74,12 @@ class XrPlaneDetection extends EventHandler {
      */
 
     _onSessionEnd() {
-        for (let i = 0; i < this._planes.length; i++) {
-            this._planes[i].destroy();
+        if (this._planes) {
```
Comment (yaustar) [inline src/xr/xr-plane-detection.js:77]: _planes can be null: https://github.com/playcanvas/engine/blob/e76b5faa9c5f34ba9a0dbde424596aaa2cfa6fd8/src/xr/xr-plane-detection.js#L35

**Review by mvaligursky — APPROVED** [review]
looks good
