### PR TITLE
eulers fix

### LINKED ISSUE #2911: Invalid Euler angles on zero scale
The way Euler angles are calculated, produces an invalid result, if the scale is set to zero. Repro:

```js
entity.setLocalScale(0, 0, 0);
entity.setEulerAngles(10, 10, 10);
    
console.log(entity.getEulerAngles()); // Vec3 { x: NaN, y: NaN, z: 0 }
```

The use case:
We have some items spawn in the world in a little animation, which scales them from zero to normal size.

### PR DESCRIPTION
**Pull request by LeXXik**
Fixes #2911 

If an entity scale is 0, the `getEulerAngles()` returns a vector with invalid (NaN) components. This change adds a check and sets eulers to 0 if scale is 0 on X or Y axis.

```js
entity.setLocalScale(0, 0, 0);
entity.setEulerAngles(10, 10, 10);
    
console.log(entity.getEulerAngles()); // Vec3 { x: NaN, y: NaN, z: 0 }
```

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by LeXXik** [comment]
To be honest, I don't really like this fix because of an additional check. Perhaps it would be better to allow division by zero, but add an `isNaN()` check in debug build and print a warning.

File: src/math/mat4.js [hunk 1]
```diff
@@ -1225,6 +1225,9 @@ class Mat4 {
         sy = scale.y;
         sz = scale.z;
 
+        if (sx === 0 || sy === 0)
```
Comment (willeastcott) [inline src/math/mat4.js:1228]: Don't you also have to check whether `z` is `0`?

**Comment by willeastcott** [comment]
I don't think doing two checks against zero is a big performance concern, to be honest.

File: src/math/mat4.js (hunk 1 above)
Comment (LeXXik) [reply src/math/mat4.js:1228]: Yes, I do, will update.

**Comment by LeXXik** [comment]
Well, it adds additional ALU for all valid reads to check an edge case. I will leave it up to your discretion.

**Review by willeastcott — APPROVED** [review]

**Comment by willeastcott** [comment]
This is great. Thanks for the fix!
