### PR TITLE
[FIX] Correctly set texture dimensions from video source

### LINKED ISSUE #4571: fitMode doesn't work on video textures
If you fork [this project](https://playcanvas.com/project/721265/overview/video-in-ui) and attempt to set the fit mode to cover for example, it won't work. The video will not play on the UI according to the fit mode you chose. It works with static images just fine, but it seems that on textures that are updated at runtime, it fails.

### PR DESCRIPTION
**Pull request by willeastcott**
Fixes #4571 

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

File: src/platform/graphics/texture.js [hunk 1]
```diff
@@ -955,8 +955,13 @@ class Texture {
                     this._levelsUpdated[mipLevel] = true;
                 }
 
-                width = source.width;
-                height = source.height;
+                if (source instanceof HTMLVideoElement) {
```
Comment (slimbuck) [inline src/platform/graphics/texture.js:958]: not sure how applicable these days, but in the graphics device we test for presence of HTMLVideoElement as well:
`(typeof HTMLVideoElement !== 'undefined' && texture instanceof HTMLVideoElement)`

**Review by slimbuck — APPROVED** [review]

File: src/platform/graphics/texture.js (hunk 1 above)
Comment (willeastcott) [reply src/platform/graphics/texture.js:958]: Oh, that's probably for running in Node? There seem to already be a couple of other `instanceof HTMLVidelElement` tests in the platform _without_ the additional guard so I think we're fine.

**Review by mvaligursky — APPROVED** [review]
