### PR TITLE
Gizmo features & fixes

### LINKED ISSUE #7892: Gizmo editor support and fixes
### Features
- [ ] Configure visibility of gizmo on translation
- [ ] Separate out colors for axes, hovering and guide lines
- [ ] Enabled all guide lines for translation vectors

### Fixes
- [ ] Fixed position warping for translation in facing direction vector plane

### PR DESCRIPTION
**Pull request by kpal81xd**
Fixes #7892

## Non-breaking changes
- All axes show on translation when dragging
- Add drag modes to set gizmo visibility state when dragging:
   - `show`: shows all shapes on drag
   - `hide`: hides all shapes on drag 
   - `selected`: only shows axes in translation/scale space
- `setTheme` method to update all colors
- Scaling stuttering for negative scaling fixed

## Deprecations
- `xAxisColor`, `yAxisColor`, `zAxisColor`, `colorAlpha` color setter/getters
- `flipShapes` boolean flag

> [!WARNING]
> The deprecation implementations cannot be combined with the new API as new API splits grouped properties into separate values

## Fixes
- Fixes gizmo translation in axis perpendicular to the camera direction to remove warping

## Checklist
- [x] I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md)
- [x] My code follows the project's coding standards
- [ ] This PR focuses on a single change

### CODE REVIEW

**Comment by mvaligursky** [comment]
We should try and avoid breaking changes by providing functionality (marked as deprecated) to convert from old to new API if possible.

File: src/extras/gizmo/scale-gizmo.js [hunk 1]
```diff
@@ -131,19 +131,33 @@ class ScaleGizmo extends TransformGizmo {
...
      *
      * @type {boolean}
      */
-    flipShapes = true;
+    flipPlanes = true;
+
+    /**
+     * Whether to hide the shapes when dragging.
+     *
+     * @type {'show' | 'hide' | 'selected'}
```
Comment (willeastcott) [inline src/extras/gizmo/scale-gizmo.js:161]: Is `selected` essentially "show the selected axis when dragging"? Maybe this needs clarifying.

Comment (kpal81xd) [reply src/extras/gizmo/scale-gizmo.js:161]: Ahh yea ill explain in the JSDoc
