### PR TITLE
fix material asset unload and reload

### LINKED ISSUE #3061: _assignTexture fault
function, MaterialHandler.prototype._assignTexture, changes materialAsset.data[Texture parameter name];
that will lead to wrong destroied Texture assigned to Material , if I unload the Texture asset and Material asset then reload them.

### PR DESCRIPTION
**Pull request by raytranuk**
Fixes #3061

This PR:
- adds a texture and cubemap `unload` event callback to clean up texture references when a texture is unloaded
- removes a not-so-robust setting of asset id to loaded resource - which was causing problems if a texture asset is unloaded and reloaded
- fixes and tidies up a calls to `_validate()` in the material json parser.

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by slimbuck** [comment]
@raytranuk could you please give an overview of the changes you've made and why in the PR description?

File: src/resources/material.js [hunk 1]
```diff
@@ -140,14 +140,14 @@ class MaterialHandler {
...
-        materialAsset.data[parameterName] = texture;
+        // NB removed swapping out asset id for resource here
         materialAsset.resource[parameterName] = texture;
     }
 
     // assign a placeholder texture while waiting for one to load
     // placeholder textures do not replace the data[parameterName] value
     // in the asset.data thus preserving the final asset id until it is loaded
-    _assignPlaceholderTexture(parameterName, materialAsset) {
+    _getPlaceholderTexture(parameterName, materialAsset) {
```
Comment (slimbuck) [inline src/resources/material.js:150]: seems like this comment is no longer valid? please update it with latest usage

File: src/resources/material.js [hunk 2]
```diff
@@ -156,7 +156,12 @@ class MaterialHandler {
         const placeholder = PLACEHOLDER_MAP[parameterName];
         const texture = this._placeholderTextures[placeholder];
 
-        materialAsset.resource[parameterName] = texture;
+        return texture;
+    }
+
+    _assignPlaceholderTexture(parameterName, materialAsset) {
```
Comment (slimbuck) [inline src/resources/material.js:162]: descriptive usage comment could be useful here

File: src/resources/parser/material/json-standard-material.js [hunk 3]
```diff
@@ -167,8 +167,9 @@ class JsonStandardMaterialParser {
         if (!this._validator) {
             this._validator = new StandardMaterialValidator();
         }
-        this._validator.validate(data);
-
+        if (!data.validated) {
```
Comment (slimbuck) [inline src/resources/parser/material/json-standard-material.js:170]: looks like `_validate` is completely unnecessary and should be removed.

it is being called from `parse()` which immediately after invoking `validate` does `initialize()`, which handles validation anyway.

File: src/resources/material.js [hunk 4]
```diff
@@ -178,8 +183,18 @@ class MaterialHandler {
         }
     }
 
+    _onTextureUnload(parameterName, materialAsset, textureAsset) {
```
Comment (slimbuck) [inline src/resources/material.js:186]: mustn't you also handle cubemap unload?

File: src/resources/material.js [hunk 5]
```diff
@@ -178,8 +183,18 @@ class MaterialHandler {
...
+        const material = materialAsset.resource;
+        if (material) {
+            if (material[parameterName] === textureAsset.resource) {
+                this._assignTexture(parameterName, materialAsset, null);
```
Comment (slimbuck) [inline src/resources/material.js:190]: should this revert to placeholder texture or is null correct?

File: src/resources/material.js (hunk 1 above)
Comment (raytranuk) [reply src/resources/material.js:150]: I'll refactor the comment

File: src/resources/material.js (hunk 2 above)
Comment (raytranuk) [reply src/resources/material.js:162]: I'll refactor the comment

File: src/resources/parser/material/json-standard-material.js (hunk 3 above)
Comment (raytranuk) [reply src/resources/parser/material/json-standard-material.js:170]: I left it in because I thought there may be code paths that would require it? There is a similar check for the `validated` property for probably similar reasons. If you are certain there are no code paths that would require the validation I can remove it.

File: src/resources/material.js (hunk 5 above)
Comment (raytranuk) [reply src/resources/material.js:190]: I wasn't certain - but the test case didn't show any errors - so decided not to change too much  - there is a null check and assigning of placeholders in the bind function so I assumed placeholders get assigned in that code path.

File: src/resources/material.js (hunk 4 above)
Comment (raytranuk) [reply src/resources/material.js:186]: ah - yes - I will add _onCubeMapUnload

File: src/resources/material.js (hunk 5 above)
Comment (raytranuk) [reply src/resources/material.js]: Found a case that would require placeholders - so now replace null with placeholders

File: src/resources/material.js (hunk 4 above)
Comment (raytranuk) [reply src/resources/material.js]: added - NB there is no existing placeholder system for cubemaps - I didn't add one in this PR - but added an issue to investigate whether they are needed: https://github.com/playcanvas/engine/issues/3076

File: src/resources/parser/material/json-standard-material.js (hunk 3 above)
Comment (raytranuk) [reply src/resources/parser/material/json-standard-material.js:164]: I tidied up the code and removed the duplication with a call to _validate (currently required in the editor thumbnail renderer).

File: src/resources/material.js (hunk 1 above)
Comment (raytranuk) [reply src/resources/material.js]: done

File: src/resources/material.js (hunk 2 above)
Comment (raytranuk) [reply src/resources/material.js:161]: done

**Review by slimbuck — APPROVED** [review]
