### PR TITLE
Fixed grid enabled/disabled

### LINKED ISSUE #7364: Grid Script throws exception when enabling after setting to disabled
It doesn't seem possible to show/hide the grid from scripts folder

Repo steps

1. go to example https://playcanvas.vercel.app/#/misc/editor
2. Modify code to set grid to globalThis
3. reload, select the correct frame in dev tools
4. type grid.enabled = false; and grid disappears as expected
5. type grid.enabled = true; and exception is thrown

Image

### PR DESCRIPTION
**Pull request by kpal81xd**
Fixes #7364
Extends GH-7365

- Sets visible property on meshInstance instead of removing and adding from the render component
- Cleans up render component if added by script

> **NOTE** There meshInstance will still be in the draw call list however since it is a single mesh instance the cost will be marginal

### CODE REVIEW

File: scripts/esm/grid.mjs [hunk 1]
```diff
@@ -320,6 +320,10 @@ class Grid extends Script {
     get resolution() {
         return this._resolution;
     }
+
+    destroy() {
+        this.entity.render.meshInstances = [];
```
Comment (willeastcott) [inline scripts/esm/grid.mjs:325]: If the script adds a render component, shouldn't destroy leave the entity in the state it was beforehand? In other words, shouldn't `removeComonent('render')` be done here instead?

Comment (willeastcott) [reply scripts/esm/grid.mjs:325]: Actually, to be precise, the script adds a render component if there wasn't one already. So maybe this should remove it if it was responsible for adding it.

**Review by willeastcott — APPROVED** [review]
