### PR TITLE
[FIX] Fall back to previous Web Audio API spec as required

### LINKED ISSUE #4137: 3D positional audio null exception on Firefox (Engine v1.52.2+)
Project: https://playcanvas.com/project/898465

Launch project on Firefox. Callstack:

(Last working version of the engine was 1.52.1)

```
TypeError: listener.positionX is undefined
    setPosition https://code.playcanvas.com/playcanvas-1.52.2.js:28069
    setCurrentListener https://code.playcanvas.com/playcanvas-1.52.2.js:47426
    onEnable https://code.playcanvas.com/playcanvas-1.52.2.js:47431
    initializeComponentData https://code.playcanvas.com/playcanvas-1.52.2.js:42931
    initializeComponentData https://code.playcanvas.com/playcanvas-1.52.2.js:47473
    addComponent https://code.playcanvas.com/playcanvas-1.52.2.js:42879
    _openComponentData https://code.playcanvas.com/playcanvas-1.52.2.js:33450
    _openComponentData https://code.playcanvas.com/playcanvas-1.52.2.js:33458
    parse https://code.playcanvas.com/playcanvas-1.52.2.js:33391
    open https://code.playcanvas.com/playcanvas-1.52.2.js:35391
    open https://launch.playcanvas.com/editor/scene/js/launch.js:18255
    open https://code.playcanvas.com/playcanvas-1.52.2.js:35323
    init https://launch.playcanvas.com/editor/scene/js/launch.js:14550
    _preloadScripts https://code.playcanvas.com/playcanvas-1.52.2.js:71156
    init https://launch.playcanvas.com/editor/scene/js/launch.js:14546
    done https://code.playcanvas.com/playcanvas-1.52.2.js:71113
    onAssetLoad https://code.playcanvas.com/playcanvas-1.52.2.js:71125
    fire https://code.playcanvas.com/playcanvas-1.52.2.js:759
    _opened https://code.playcanvas.com/playcanvas-1.52.2.js:38205
    _loaded https://code.playcanvas.com/playcanvas-1.52.2.js:38229
    _onSuccess https://code.playcanvas.com/playcanvas-1.52.2.js:35297
    handleLoad https://code.playcanvas.com/playcanvas-1.52.2.js:35247
    success https://code.playcanvas.com/playcanvas-1.52.2.js:32173`
```

### PR DESCRIPTION
**Pull request by willeastcott**
Adhere to the 'up-to-date' Web Audio API specification, but do not assume it is always supported. Instead, fallback to older versions of the spec as required. At the time of writing, Firefox still only implements a previous version of the spec.

This PR also takes to opportunity to officially deprecate/retire API related to listener/sound velocity.

Tested on Windows 10 in:

* IE11
* Chrome
* Firefox

Fixes #4137

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

File: src/audio/channel3d.js [hunk 1]
```diff
@@ -162,10 +170,6 @@ if (!hasAudioContext()) {
             }
         },
 
-        setVelocity: function (velocity) {
-            this.velocity.copy(velocity);
-        },
-
```
Comment (jpauloruschel) [inline src/audio/channel3d.js:168]: To confirm, by removing this line, will the default implementation (on lines 70-72) be used?

**Review by jpauloruschel — APPROVED** [review]

File: src/audio/channel3d.js (hunk 1 above)
Comment (willeastcott) [reply src/audio/channel3d.js:168]: Correct! 😄
