### PR TITLE
Physics engine optimizations

### LINKED ISSUE #1992: Kinematic body handling is very inefficient (and wrong)
Currently, kinematic bodies are updated every frame via the `_updateKinematic` function:

```
        /**
         * @private
         * @function
         * @name pc.RigidBodyComponent#_updateKinematic
         * @description Kinematic objects maintain their own linear and angular velocities. This method updates their transform
         * based on their current velocity. It is called in every frame in the main physics update loop, after the simulation is stepped.
         * @param {number} dt - Delta time for the current frame.
         */
        _updateKinematic: function (dt) {
            this._displacement.copy(this._linearVelocity).scale(dt);
            this.entity.translate(this._displacement);

            this._displacement.copy(this._angularVelocity).scale(dt);
            this.entity.rotate(this._displacement.x, this._displacement.y, this._displacement.z);
            if (this.body.getMotionState()) {
                var pos = this.entity.getPosition();
                var rot = this.entity.getRotation();

                ammoTransform.getOrigin().setValue(pos.x, pos.y, pos.z);
                ammoQuat.setValue(rot.x, rot.y, rot.z, rot.w);
                ammoTransform.setRotation(ammoQuat);
                this.body.getMotionState().setWorldTransform(ammoTransform);
            }
        },
```

This looks wrong. Kinematic bodies should just be updated based on the parent entity's world transformation matrix. Linear and angular velocity are irrelevant. So, instead, the code should be something like:

```
        _updateKinematic: function () {
            var body = this.body;
            if (body) {
                var motionState = body.getMotionState();
                if (motionState) {
                    var wtm = this.entity.getWorldTransform();

                    ammoTransform.setFromOpenGLMatrix(wtm.data);

                    motionState.setWorldTransform(ammoTransform);
                }
            }
        },
```

This is far, far faster than the original code.

Also, at the moment, the engine updates kinematic bodies _after_ stepping the simulation. Again, this is wrong. Kinematic bodies should be updated before the simulation is stepped.

The following scene has over 1000 kinematic bodies:

https://launch.playcanvas.com/480301

The CPU time almost halves with the above changes.

CCing @daredevildave because I believe he wrote this code originally. Would be great to get your thoughts.

### PR DESCRIPTION
**Pull request by willeastcott**
This PR optimizes the rigidbody and collision components. For some physics-heavy applications, the speed up is very significant (up to ~2x is possible).

Specifically, the PR:

* Moves all physics update into the `pc.RigidBodyComponentSystem`. The collision component system now does zero update. This means that the order in which the physics world is updated can be strictly controlled.
* Avoids all the per-frame checks for whether each body needs to be processed.
* Moves the updating of kinematic body transforms to *before* the stepping of the physics simulation.
* Optimizes the `_updateKinematic` function to be much faster. It no longer takes velocities into account and just tracks the world transform of the entity.
* Moves the long-deprecated `pc.RigidBodyComponent#bodyType` to backwards-compatibility.js.

Benchmark (Win10 laptop + Chrome):

The ['Creating Rigid Bodies in Code' scene](https://launch.playcanvas.com/480301) has gone from ~16.5ms to ~9.5ms per frame on the CPU.

Fixes #1992 

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

File: src/framework/components/rigid-body/component.js [hunk 1]
```diff
@@ -709,22 +698,18 @@ Object.assign(pc, function () {
          * @name pc.RigidBodyComponent#_updateKinematic
          * @description Kinematic objects maintain their own linear and angular velocities. This method updates their transform
```
Comment (slimbuck) [inline src/framework/components/rigid-body/component.js:699]: Might be worth updating the description.

Comment (willeastcott) [reply src/framework/components/rigid-body/component.js]: Done. :)

File: src/framework/components/rigid-body/component.js [hunk 2]
```diff
@@ -604,28 +618,19 @@ Object.assign(pc, function () {
...
-
-                var transform = body.getWorldTransform();
-                var origin = transform.getOrigin();
-                origin.setValue(pos.x, pos.y, pos.z);
+                var wtm = this.entity.getWorldTransform();
+                ammoTransform.setFromOpenGLMatrix(wtm.data);
 
-                ammoQuat.setValue(rot.x, rot.y, rot.z, rot.w);
-                transform.setRotation(ammoQuat);
+                body.setWorldTransform(ammoTransform);
```
Comment (slimbuck) [inline src/framework/components/rigid-body/component.js:626]: Wondering what the difference is between body.setWorldTransform() and body.motionState.setWorldTransform()?

Why does this sync function sync both, but _updateKinematic only sets body.motionState?

Comment (willeastcott) [reply src/framework/components/rigid-body/component.js:626]: Exactly. I _think_ it's unnecessary. But right now, I'm trying not to break anything. 😄 This function could be modified further...

Comment (willeastcott) [reply src/framework/components/rigid-body/component.js:626]: For kinematics, yeah, you just need to set the motion state. I'm trying to figure out what needs to be done for all body types.

Comment (willeastcott) [reply src/framework/components/rigid-body/component.js:620]: I just read the [Bullet manual](https://github.com/bulletphysics/bullet3/blob/master/docs/Bullet_User_Manual.pdf) - see page 20. It says:

```
If you attempt to ask a body for its position through btCollisionObject::getWorldTransform
or btRigidBody::getCenterOfMassTransform, it will return the position at the end of the last
physics tick. That's useful for many things, but for rendering you will want some interpolation. Bullet
interpolates the transform of the body before passing the value to setWorldTransform.
If you want the non-interpolated position of a body [which will be the position as it was calculated at
the end of the last physics tick], use btRigidBody::getWorldTransform() and query the body directly.
```

**Comment by maxbbb** [comment]
Hey so I was running into some problems with this branch and seeing now that's pulled into master. Changing the position of a static body moves the model but does not move the rigidbody and kinematic objects just do not collide with anything anymore. Here is a demo project that shows the static body issue, and if you switch the floor to kinematic you'll see that the objects fall right through. 

[Demo Link](https://launch.playcanvas.com/924240?use_local_engine=https://code.playcanvas.com/playcanvas-latest.js)

[Demo Project](https://playcanvas.com/project/687891/overview/basic-physics)

**Comment by willeastcott** [comment]
I'm confused. Your demo scene does the same thing with the stable engine _and_ the latest dev engine.

**Comment by maxbbb** [comment]
Okay so looks like you could never move static bodies if they were default enabled in the editor, I must have not noticed this as I usually create them programmatically and set their positions before enabling them. I'm not sure if that is the expected behavior or not. I've changed the demo to show the kinematic floor by default and that does behave correctly on the most stable version but does not on the dev version.

**Comment by willeastcott** [comment]
OK, I'll check it out.

**Comment by willeastcott** [comment]
Are you currently modifying this demo? I see you're in the scene. I can't quite repro what you describe.

**Comment by maxbbb** [comment]
No I am not, I just had the browser tab open. That's interesting I've tried on every browser and a different computer and I'm getting the same result. It's working fine for you with [this](https://launch.playcanvas.com/924240?use_local_engine=https://code.playcanvas.com/playcanvas-latest.js) link?

**Comment by willeastcott** [comment]
Sorry, ignore me. I was using the stable engine. 🤦

**Comment by willeastcott** [comment]
OK, I've fixed it. The problem is that the refactored physics engine was passing any scale on an entity's world transform into Ammo. Previously, the engine would explictly ignore scale and just set position and rotation of bodies. I've restored that behavior. It does cost a little performance, but it's still a _lot_ faster than it was. Plus, I can probably find another way to optimize the passing of transforms between entities and bodies.

PR incoming! 🎉

**Comment by maxbbb** [comment]
Awesome! Thank you 😊

**Comment by willeastcott** [comment]
OK @maxbbb - that's now merged to master! I hereby challenge you, good sir, to find any more bugs! 😄

**Comment by maxbbb** [comment]
Unfortunately I think I've found another 😞 however this happens in all the previous versions. Compound dynamic bodies created in the editor are behaving very oddly. Even if there is only one child and that child is setup the same way as a regular primitive rigidbody, the behavior it very different. Same project - [1.27.0](https://launch.playcanvas.com/924240?use_local_engine=https://code.playcanvas.com/playcanvas-1.27.0.js) and [1.28.0](https://launch.playcanvas.com/924240?use_local_engine=https://code.playcanvas.com/playcanvas-latest.js)

I looked at your falling chair demo which clearly works, which makes me think it is something specific to the editor. Also because this is not something specific to this new update would you like me to open a new issue for it?

**Comment by willeastcott** [comment]
Yep, I think it warrants a new issue. 😄  Thanks!
